### ISSUE TITLE
y-axis label issues

### ISSUE THREAD

**Issue by bensfisher** [sjPlot/devel#100]
Having issues with sjPlot printing the entire output to the y-axis labels, instead of just the variable names. This appears to be a problem with both sj.glm and sj.lm. I'm using the most recent versions of R, ggplot2, and sjPlot.

![sjplot](https://cloud.githubusercontent.com/assets/4095512/12819667/fae12626-cb29-11e5-8e6a-da1c4a3c2e6f.png)

**Comment by helix123** [comment]
Could be related to #96. Have you tried the latest version of sjPlot from GitHub?

**Comment by bensfisher** [comment]
You're right. Apologies for missing that!
