### ISSUE TITLE
sjt.xtab ignores valueLabels and variableLabels

### ISSUE THREAD

**Issue by hbaize** [sjPlot/devel#101]
sjt.xtab does not use supplied valueLabels. It instead uses actual variable values. Also, does not wrap the variableLabels. In addition, the bottom double line does not extend the full width of the table. 

Version 1.9

reproducible code: 
x <- factor(c("c","c","c","2","2","2","2","3","3"), 
            levels = c("1","2","3","4","5","c"))
y <- factor(c("P","P","P","P","Y","Y","P","Y","P"))
      
vallab <- list(c("Refused","Impaired","Language","Other",
                 "No Data","Completed Survey"), 
               c("Parent","Youth"))
varlab <- c("Completion Status","Respondent Type With Long Title not wapped")               
      
sjt.xtab(x,y,
         variableLabels = varlab,
         valueLabels = vallab, 
         showLegend = FALSE,
         showColPerc = TRUE,
         showSummary=FALSE,
         )$knitr

Thanks in advance for your attention. :)

**Comment by sjPlot** [comment]
Damn, too radical code cleaning ;-)
I found the bug and will fix it in the course of this das.
