### ISSUE TITLE
Error when using sjp.int() with finding 'sj.setGeomColors'

### ISSUE THREAD

**Issue by rsulli01** [sjPlot/devel#102]
I have accessed the sjPlot and am trying to use the function:
sjp.int(fit, type = "cond"),
but I get an error code of:
Error: could not find function "sj.setGeomColors".
Is there some code I am missing or is it something I am supposed to access?

**Comment by sjPlot** [comment]
It seems like you have compiled the function, so it's part of your environment. I suggest cleaning the workspace and see if ir helps.

**Comment by sjPlot** [comment]
If [this](http://stackoverflow.com/q/35216115/2094622) is also your post, I would say it's due to the environment. R first searches the environment for functions, however, the function in your environment cannot access the helper-functions of the sjPlot package. Hence the warning / error.

**Comment by rsulli01** [comment]
It worked! Thank you!
