### ISSUE TITLE
three way continuous interactions

### ISSUE THREAD

**Issue by nkcaselli** [sjPlot/devel#103]
I have a three way interaction between three continuous variables in a lmer. I'd love to use sjPlot to visualize the interaction.

**Comment by sjPlot** [comment]
I thought this issue would have been easier to solve, however, it requires some re-writing or adding of code. I have to find a good concept of which values to choose for the third interaction term, so the output does not contain dozens of plots...

**Comment by nkcaselli** [comment]
I am not surprised that it isn't a simple fix. It isn't clear how to choose which "view" of that data is the right one to plot (i.e. Which should be the third interaction term). A related challenge is that it also isn't clear to me how to determine whether the slope of any given line in an interaction plot is different from zero if there is no main effect. I wish you the best, and look forward to hearing what you come up with.

**Comment by sjPlot** [comment]
I just stumbled upon this issue, and realised that you can plot 3-way-interaction, simply by using `type = "pred"`. This should work for most cases, an example:

```
library(sjPlot)
library(sjmisc)
data(efc)
# create binary response
y <- ifelse(efc$neg_c_7 < median(stats::na.omit(efc$neg_c_7)), 0, 1)
# create data frame for fitted model
mydf <- data.frame(y = as.factor(y),
                   sex = as.factor(efc$c161sex),
                   edu = as.factor(efc$c172code),
                   barthel = as.numeric(efc$barthtot))
# fit model
fit <- glm(y ~ sex * barthel * edu, data = mydf, family = binomial(link = "logit"))

sjp.glm(fit, type = "pred", vars = c("barthel", "sex", "edu"), facet.grid = F, show.ci = F)
```

This mostly requires the 2nd and 3rd term to be categorical. If you have continuous variables as "grouping" variable (i.e. if you have 2 or more numeric, continuous variables in your interaction term), you could also use the `ggpredict()`-function from my new `ggtidyr`-package. This will be implemented in sjPlot, once ggtidyr is released on CRAN, and allows more flexible plotting in sjPlot.

```
library(sjmisc)
library(ggplot2)
library(ggtidyr) # install with devtools from GitHub
data(efc)
# create binary response
y <- ifelse(efc$neg_c_7 < median(stats::na.omit(efc$neg_c_7)), 0, 1)
# create data frame for fitted model
mydf <- data.frame(y = as.factor(y),
                   hours = as.numeric(efc$c12hour),
                   edu = as.factor(efc$c172code),
                   barthel = as.numeric(efc$barthtot))

# fit model, 3-way-interaction with 2 continuous vars.
fit <- glm(y ~ hours * barthel * edu, data = mydf, family = binomial(link = "logit"))

# predict data, selecting the value "10", "20" and "42" from continuous 
# variable "hours" as "grouping"-levels
dat <- ggpredict(fit, vars = c("barthel", "hours [10, 20, 42]", "edu"))

# manually plot the data
ggplot(dat, aes(x = x, y = predicted, colour = as.factor(group))) +
  stat_smooth(method = "glm", se = F, fullrange = T) +
  facet_wrap(~facet)
```

**Comment by benjaminwnelson** [comment]
Is there anyway to adapt this function to visualize data in line with [this](https://journals.sagepub.com/doi/abs/10.1177/2515245917746792?journalCode=ampa) paper? Specifically, to visualize potential "small multiples" as shown in this figure? Thanks for making so many great packages!

<img width="852" alt="Screen Shot 2020-12-04 at 4 55 13 PM" src="https://user-images.githubusercontent.com/36683142/101218656-7b129b80-3651-11eb-8ac8-56e559b2a1bc.png">

**Comment by strengejacke** [comment]
In general, you could create such plot (using [ggeffects](http://strengejacke.github.io/ggeffects)), however, when the second term is also continuous, and you plot at specific values (like above, -2 SD, -1 SD, 0, +1 SD and +2 SD), then these values mostly have few exact matches in the raw data - and at the moment, raw data is added to each facet depending on an "exact match".

See example below: I plot Sepal.Length at value 3 to 7, however, the "real" values of Sepal.Length in iris also include 4.1, 7.9 etc. And these values do not match with my "at-values" 3 to 7. Hence, for the raw data, new facets are created.

But it works with categorical predictors (see 2nd plot).

``` r
library(ggeffects)
m <- lm(Sepal.Width ~ Petal.Width * Sepal.Length, data = iris)
pr <- ggpredict(m, c("Petal.Width", "Sepal.Length [3,4,5,6,7]"))
plot(pr, add.data = TRUE, facets = TRUE)
#> Loading required namespace: ggplot2
```

![](https://i.imgur.com/f7SsUJ1.png)

``` r

m <- lm(Sepal.Width ~ Petal.Width * Species, data = iris)
pr <- ggpredict(m, c("Petal.Width", "Species"))
plot(pr, add.data = TRUE, facets = TRUE)
```

![](https://i.imgur.com/MLPWVJM.png)

<sup>Created on 2020-12-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
The first example works better w/o facetting:

``` r
library(ggeffects)
m <- lm(Sepal.Width ~ Petal.Width * Sepal.Length, data = iris)
pr <- ggpredict(m, c("Petal.Width", "Sepal.Length [4,6,8]"))
plot(pr, add.data = TRUE, facets = FALSE, ci = FALSE)
#> Loading required namespace: ggplot2
```

![](https://i.imgur.com/yItRiKj.png)

<sup>Created on 2020-12-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
