### ISSUE TITLE
Standardized estimates of fixed effects 

### ISSUE THREAD

**Issue by cristiantb** [sjPlot/devel#105]
Dear Daniel,
I am using the library "sjPlot" to plot the beta's of a mixed model. If previously I standardise my variables to get standardized coefficients I use:
`sjp.lmer(myMODEL, type = "fe") `
If I do not standardize my variables I do not get standardized coefficients so I use:
`sjp.lmer(myMODEL, type = "fe.std") `
My issue is that I get different results for categorical variables and the same results for continuos. Are you standardizing both type of variables in `type = "fe.std"`? Does it make sense to standardize categorical variables?

Thank you in advance.
Cristian-

**Comment by sjPlot** [comment]
I'm using [this method](http://stackoverflow.com/a/26206119/2094622) suggested by Ben Bolker. It may be that factors with more than 2 caregories are not properly standardized because they are not treated as dummy. In such case, use `sjmisc::to_dummy` to create binary predictors for your model.

**Comment by sjPlot** [comment]
I'll close this issue now - if you still encounter bugs or have any suggestions, please re-open it.
