### ISSUE TITLE
sjp.likert plots categories in the wrong order when cat.neutral < catcount 

### ISSUE THREAD

**Issue by douglaswhitaker** [sjPlot/devel#109]
When using the sjp.likert function to plot survey responses when the neutral category is in the middle (e.g. a "3" for Neutral on a 5-point likert-type from Strongly Disagree,1 to Strongly Agree, 5), the responses are plotted in the wrong order. Specifically, sjp.likert will **swap** the values of 3 and 5 in this instance. When the neutral category is the largest value, there are no problems. This behavior appears in the examples for the function on [http://www.strengejacke.de/sjPlot/sjp.likert/](http://www.strengejacke.de/sjPlot/sjp.likert/). Some minimal example code based on these examples follows.

```
set.seed(1)
require(sjPlot);
# prepare data for 4-category likert scale, with neutral category 5 items
mydf <- data.frame(q1 = as.factor(sample(1 : 5, 500, replace = TRUE,
                                         prob = c(0.2,0.3,0.1,0.35,0.05))),
                   q2 = as.factor(sample(1 : 5, 500, replace = TRUE,
                                         prob = c(0.5,0.25,0.15,0.1,0.0))),
                   q3 = as.factor(sample(1 : 5, 500, replace = TRUE,
                                         prob = c(0.22,0.1,0.38,0.27,0.03))),
                   q4 = as.factor(sample(1 : 5, 500, replace = TRUE,
                                         prob = c(0.08,0.14,0.41,0.24,0.13))),
                   q5 = as.factor(sample(1 : 5, 500, replace = TRUE,
                                         prob = c(0.37,0.23,0.13,0.24, 0.03))))
# create labels
labels <- c("Strongly agree",
            "Agree",
            "Disagree",
            "Strongly Disagree",
            "Don't know/Neither")

table(mydf[,1])/500

sjp.likert(mydf,
           cat.neutral = 5, # "5" is value for "don't know"
           legendLabels = labels,
           title = "Neutral Category is 5")

sjp.likert(mydf,
           cat.neutral = 3, # "3" is value for "neither"
           legendLabels = labels,
           title = "Neutral Category is 3")
```

This code produces the following responses per item for Q1:

```
    1     2     3     4     5 
0.188 0.312 0.100 0.350 0.050 
```
If 5 is the neutral category, then the plot is correct.
![neutral-is-5-correct](https://cloud.githubusercontent.com/assets/11415345/13382220/2671a358-de3d-11e5-8990-f2489e839e64.png)
If 3 is the neutral category, the "Strongly Disagree" bar should represent 5% and the "Disagree" bar should represent 35%. Instead, the "Strongly Disagree" bar always remains 35% because of the swapping behavior.
![neutral-is-3-incorrect](https://cloud.githubusercontent.com/assets/11415345/13382221/2b2a8310-de3d-11e5-94d0-75b3a90cf9e8.png)
This behavior occurs with larger numbers of categories, e.g. with 7 categories and "4" being neutral. Only the 7 and 4 swap here. 

I believe this behavior is because of the way sjmisc::rec() is used inside the sjp.likert() function:

```
    if (!is.null(cat.neutral) && cat.neutral <= catcount) { 
      items[[i]] <- sjmisc::rec(items[[i]], sprintf("%i=%i;%i=%i;else=copy",
                                                    cat.neutral, catcount + 1, catcount + 1, cat.neutral))
    }
```
In this code, there is only one swap. In order for it to produce a correct output, multiple swaps must occur. 

To circumvent this behavior, I have been using a small function which recodes the data to have the neutral category as the highest value because there are no problems with this plotting. For example:

```
recoder <- function(data, neutral.value, max.value){
  data[data==neutral.value] <- max.value + 1;
  for (i in (neutral.value+1):(max.value+1)){
    data[data==i] <- i-1;
  }
  return(data);
}
```
This is used as below, which produces the correct plot. ("as.factor" is removed because recoder is a very simple function which cannot handle factors, but this isn't important for the solution to the problem.)
```
set.seed(1)
# Note as.factor removed because recoder() is simple and cannot handle factors
mydf <- data.frame(q1 = (sample(1 : 5, 500, replace = TRUE,
                                         prob = c(0.2,0.3,0.1,0.35,0.05))),
                   q2 = (sample(1 : 5, 500, replace = TRUE,
                                         prob = c(0.5,0.25,0.15,0.1,0.0))),
                   q3 = (sample(1 : 5, 500, replace = TRUE,
                                         prob = c(0.22,0.1,0.38,0.27,0.03))),
                   q4 = (sample(1 : 5, 500, replace = TRUE,
                                         prob = c(0.08,0.14,0.41,0.24,0.13))),
                   q5 = (sample(1 : 5, 500, replace = TRUE,
                                         prob = c(0.37,0.23,0.13,0.24, 0.03))))
mydf.kludge <- recoder(mydf, neutral.value=3, max.value=5)
sjp.likert(mydf.kludge,
           cat.neutral = 5, # "3" is "neither" but we adjusted for this using recoder()
           legendLabels = labels,
           title = "Neutral Category is 3, with Kludge")
```
![neutral-is-3-correct](https://cloud.githubusercontent.com/assets/11415345/13382223/38d74d2c-de3d-11e5-9121-a6f74d6a9ab5.png)

I believe there are three different ways to solve this problem, but I don't know what you feel is most in the spirit of sjPlot.

1. Adding a loop inside sjp.likert() which calls sjmisc::rec() several times to make the appropriate swaps.
2. Silently recoding the data to fit the working case of the largest value being neutral, i.e. if cat.neutral < catcount then call a function like recoder() to make all the swaps at the beginning of the function without user intervention.
3. Adding a function to the sjPlot package like recoder() which users can use to make their data fit the appropriate format for sjp.likert() with neutral as the largest value. This is not desirable, though, because changing the original data can ruin/prevent other analyses.

**Comment by sjPlot** [comment]
Thanks, I (hopefully) fixed the bug and am now using following code in `sjp.likert`:

    if (!is.null(cat.neutral) && cat.neutral <= catcount) {
      # first, each other category has to be moved down one position
      # therefore, we create a pattern with values from neutral
      # category to category count
      downvote <- seq(cat.neutral, catcount + 1, by = 1)
      # now we "shift" this value pattern and make a
      # string out of it
      recode.pattern <- paste0(paste0(sprintf("%i=%i",
                                              c(downvote[-1], downvote[1]),
                                              downvote),
                                      collapse = ";"), ";else=copy")
      # finally, recode data
      items[[i]] <- sjmisc::rec(items[[i]], recodes = recode.pattern)
    }

At least for your examples, the plot is correct now. I'll submit the changes tonight.
