### ISSUE TITLE
Y-axis text in sjp.lmer

### ISSUE THREAD

**Issue by AnthonyBarnett** [sjPlot/devel#110]
Hi Daniel,
I'm using sjp.lmer to plot a linear mixed model with random intercept and slope.
**Model**
>METS2<-METS^2
>VArandomIntSLQ <-lmer(Acc ~ METS + METS2 + (1 + METS + METS2 |part), data = cut_point, REML=FALSE)
>summary(VArandomIntSLQ)

**sjPlot**
>sjp.lmer(VMranIntSLQ, type = "poly", poly.term = "METS", geom.colors = c("#111111"), axisTitle.x = "METS", axisTitle.y = NULL)

The graph is fine, but the y-axis title is generic ("response") no matter what I enter with regard to axisTitle.y = . Even if I leave this command out, the default "response" still appears. 

Grateful if you could advise me as to how to get a y-axis title on the graph. I'm very new to R.

Cheers,
Anthony

**Comment by sjPlot** [comment]
Added options, so you can use `axisTitle.x` and `axisTitle.y`, or by default, variable names are used.
