### ISSUE TITLE
Package Load Fails

### ISSUE THREAD

**Issue by LauraDecker** [sjPlot/devel#113]
I'm fairly new to R. I have installed sjPlot in the library, but when I try to load I receive an error message.I thought my version of R might be too outdated, so I uninstalled and reinstalled the most recent version. However, the program still won't load.

> library(sjPlot)
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘pbkrtest’
Error: package or namespace load failed for ‘sjPlot’

**Comment by sjPlot** [comment]
To not reinvent the wheel each time, most packages depend on functions of other packages. Hence, when installing a package, you most likely have to install its dependencies as well (which is usually done automatically). However, a package's dependency (package) may depend on another package as well, which probably was not installed.

When installing and setting up R for the first time, I usually manually install basic packages step by step, to ensure I have all dependencies installed as well.

In your case, package **pbkrtest** is missing, so you have to install it. However, you also may go through the following installation process, which will install dozens of packages, which are - however - quite useful or even necessary dependencies.

    # data wrangling
    install.packages(c("dplyr", "tidyr", "broom", "reshape2"), dependencies = TRUE)
    # data import
    install.packages(c("haven", "readr", "readxl"), dependencies = TRUE)
    # regression tools
    install.packages(c("lme4", "car", "rms", "arm", "lmtest", "lmerTest", "lsmeans"), dependencies = TRUE)
    # misc
    install.packages(c("Hmisc", "sjmisc", "vcd", "effects"), dependencies = TRUE)
    # graphics
    install.packages(c("ggplot2", "lattice"), dependencies = TRUE)

This list is incomplete, and just what I recall when I'm doing a fresh R installation. But I think it covers most of the basics (and some more) of what you may need...

**Comment by LauraDecker** [comment]
Thank you!
