### ISSUE TITLE
editing facets created with sjp.int

### ISSUE THREAD

**Issue by catmarais** [sjPlot/devel#115]
As far as I understand, when using sjp.int with facet.grid = TRUE, it is impossible to reorder facets and rename their lables?

**Comment by sjPlot** [comment]
The facet-order is determined by the order of the factor levels of the moderator values. Reorder factor levels, and facets will be reordered as well.

facet labels are, currently for `type = "eff"`, now automatically retrieved from the value label attributes (see `sjmisc::get_labels()`). If the moderator variable has no value labels, its factor levels are used as facet title. Labelling facets is still a small pain in ggplot, though it has improved to previous versions.

I'll see if I can also automatically use value labels for `type = "cond"` on facetting, and if so, I'll close this issue.
