### ISSUE TITLE
new version cannot be installed or used in Rstudio

### ISSUE THREAD

**Issue by zyevelyn** [sjPlot/devel#117]
Hi, After sjp.int() was fixed yesterday, I tried to reinstall the package. However, I cannot do it. The error massage: Error in get(Info[i, 1], envir = env) :  cannot allocate memory block of size 4.0 Gb

**Comment by sjPlot** [comment]
I don't see how this error could be related to my package. It might be that you have to update your packages first, so all dependencies of sjPlot are up to date. For insance, **sjmisc** version 1.6 is required for the current dev-build of **sjPlot**.

**Comment by zyevelyn** [comment]
Thanks!
