### ISSUE TITLE
using sjt.df with describe() with changed  parameter 

### ISSUE THREAD

**Issue by EvgeniaTs** [sjPlot/devel#118]
I want to use function describe()  but with changed  parameter eg describe(x,trim=1)
Is this possible using sjt.df ?
Thanks
Evgenia

**Comment by sjPlot** [comment]
No, currently not, but I'll implement an option so you can add parameters to `sjt.df`, which will then be passed down to `describe`.

**Comment by sjPlot** [comment]
Ok, closed with latest commit: https://github.com/sjPlot/devel/commit/5e8a8276ae8b18caadb08a8b2f213ade5c6dda6b
