### ISSUE TITLE
Unexpected changes with ggplot2

### ISSUE THREAD

**Issue by hbaize** [sjPlot/devel#119]
When ggplot2 was updated a few months ago it changed sjp.stackfrq output. Attached are examples of old and new. The file ending in XX is how it looks now. It no longer has boxed outline on the bars, and the legend is stacked instead of on one line. 
It would be nice if ggplot wouldn't change in ways that break code. ;( 

Harold
![psathealthright 360 detox center buena vista](https://cloud.githubusercontent.com/assets/17073646/13967525/e1911638-f034-11e5-9f88-69ef7d78a434.jpg)
![psathealthright 360 detox center buena vista_xx](https://cloud.githubusercontent.com/assets/17073646/13967526/e46e196e-f034-11e5-977b-2c631f7e9153.jpg)

**Comment by sjPlot** [comment]
At least according to the outline, you can use following work around:
`ggplot2::update_geom_defaults("bar", list(colour = "black"))`

I'll see how width of legend is affected and can be changed.

**Comment by sjPlot** [comment]
Ok, the first issue is fixed, `geom.outline.color` now works again in `sjp.setTheme`. I'll commit an update soon.

For the second one, you need to replace the scale, manually defining the amount of rows / columns for the legend:

`last_plot() + scale_fill_brewer(guide = guide_legend(nrow = 1))`

should work...

**Comment by hbaize** [comment]
Great!

Thanks Daniel. That will be a lot better than reverting to the old version of ggplot2. Using the old version was causing incompatibility with other things.


Thanks again,



Harold R. Baize, PhD
Data Analyst
Office of Quality Management
Behavioral Health Services
San Francisco Health Network
1380 Howard St., Rm 224e
San Francisco, CA  94103
415-255-3690
Fax 415-252-3030

This e-mail is intended for the recipient only.  If Protected Health Information (PHI) is contained in this email, unauthorized disclosure may subject the discloser to civil or criminal penalties under state and federal privacy laws. If you received this email in error, notify me and destroy the email immediately.


________________________________

**Comment by hbaize** [comment]
Daniel,
How do I add "last_plot() + scale_fill_brewer(guide = guide_legend(nrow = 1))" ?
This isn't working:
sjp.stackfrq(as.data.frame(psatotf[,11:1]), 
           title = "Satisfaction Survey",
           legendLabels = lbs,
           breakLegendLabelsAt = 6,
           breakLabelsAt = 60,
           geom.size = 0.7,
           axisLabels.y = itx[11:1], 
           includeN = FALSE,
           showValueLabels = FALSE,
           geom.colors = gcolors, 
           )
           + scale_fill_brewer(guide = guide_legend(nrow = 1))

Thanks in adavnce

**Comment by hbaize** [comment]
Okay, i figured it out. I didn't realize that "last_plot()" was literal and required. Essentially I have to add code to recreate the entire fill just to modify the number of rows! 
This works:
sjp.stackfrq(as.data.frame(psatotf[,11:1]), 
           title = "Satisfaction Survey",
           legendLabels = lbs,
           breakLegendLabelsAt = 6,
           breakLabelsAt = 60,
           geom.size = 0.7,
           axisLabels.y = itx[11:1], 
           includeN = FALSE,
           showValueLabels = FALSE,
           geom.colors = gcolors, 
           )
    last_plot() + scale_fill_manual(values = gcolors,
                               labels = lbs,
                               guide = guide_legend(nrow = 1))

**Comment by sjPlot** [comment]
You can also directly add ggplot-layers to the plot-return value:

```
sjp.stackfrq(<your stuff here>)$plot + scale_fill_manual(values = gcolors,
  labels = lbs,
  guide = guide_legend(nrow = 1))
```

**Comment by hbaize** [comment]
Yes I tried scale_fill_brewer, it results in a warning message and loss of colors/labels. 

"Scale for 'fill' is already present. Adding another scale for 'fill', which will replace the
existing scale." 

Then I switched to scale_fill_manual, and added the specification of color and label, although it produces the same warning. Perhaps both work and produce the warning.

**Comment by sjPlot** [comment]
I just recognized that you specify `geom.colors`, so indeed a manual scale is used, not the brewer scale.
