### ISSUE TITLE
view.df empty values column 

### ISSUE THREAD

**Issue by EvgeniaTs** [sjPlot/devel#120]
I use world95 <- read.spss('02world95.sav', to.data.frame=T, reencode=TRUE) to read a dataset located in SPSS sample files
When i use view_df(world95[,-1]) I take an empty column for values
Why this happen?
Thanks alot 
Evgenia

**Comment by sjPlot** [comment]
Could you please provide some data, e.g. sending me the data file via email?

**Comment by EvgeniaTs** [comment]
I'm attaching the datafile
Thanks for your quick response
Evgenia

**Comment by sjPlot** [comment]
I have not received any data yet- have you already sent your data?

**Comment by EvgeniaTs** [comment]
Yes i send it immediately after your email 
I am spending you again tomorrow morning 
Thanks 
Evgenia 

Εστάλη από το Sony Xperia™ smartphone

---- Ο χρήστης Daniel Lüdecke έγραψε ----

**Comment by EvgeniaTs** [comment]
I am sending you the file
Please notice that you received it this time
Evgenia

**Comment by sjPlot** [comment]
Still received no mail. Are you sending to d.luedecke@uke.de?

**Comment by sjPlot** [comment]
When you use the `foreign` library, variable labels are attached as attributes to the complete data frame, not to each vector/variable. Thus, when you select specific columns, this attribute list no longer matches to the count of columns.

To work with labelled data, you first have to set variable labels to each variable (see code below), or you use the `read_spss` function from the **sjmisc**-package, which does this automatically for you.

```
library(foreign)
library(sjmisc)
world95 <- read.spss("world95.sav", to.data.frame = TRUE, reencode = TRUE)
set_label(world95) <- get_label(world95)
view_df(world95)
view_df(world95[, -1])
```

or

```
library(sjmisc)
world95 <- read_spss("world95.sav")
view_df(world95)
view_df(world95[, -1])
```
