### ISSUE TITLE
Sjp plot "rs.ri": Undefined columns selected"

### ISSUE THREAD

**Issue by PS80** [sjPlot/devel#121]
Hi, 

I tried to plot the random slopes of my model using the sjp.plot command in R. Unfortunately, I get the error "undefined columns selected". I guess the problem stems from my attempt to plot the random slopes for a three-level model? I could not find a solution for this problem. 

Any help is appreciated.

Best,
Peter

**Comment by sjPlot** [comment]
Do you have a reproducible example? How does your model formula look like?
