### ISSUE TITLE
Relative CI in returned sjp.frq() data.frame

### ISSUE THREAD

**Issue by ipuzek** [sjPlot/devel#123]
Hello,

it seems that relative confidence intervals are not computed correctly.

E.g. this:
sjp.frq(mtcars$cyl)$mydf

Upper and lower relative confidence intervals just do not make sense. I checked in the code, they should be calculated as upper.ci / total_sum , but it seems that they are not.

Best regards,
Ivan

**Comment by sjPlot** [comment]
This is the code I use to compute the confidence intervals:

```
  total_sum = sum(x, na.rm = T)
  rel_frq <- as.numeric(mydat$frq / total_sum)
  ci <- 1.96 * suppressWarnings(sqrt(rel_frq * (1 - rel_frq) / total_sum))
  mydat$upper.ci <- total_sum * (rel_frq + ci)
  mydat$lower.ci <- total_sum * (rel_frq - ci)
  mydat$rel.upper.ci <- rel_frq + ci
  mydat$rel.lower.ci <- rel_frq - ci
```

So, `mydat$upper.ci <- total_sum * (rel_frq + ci)` is the upper CI, and divided by `total_sum` would be:
`mydat$upper.ci / total_sum = total_sum * (rel_frq + ci) / total_sum = rel_frq + ci`

which is: `  mydat$rel.upper.ci <- rel_frq + ci`

So, if there's a mistake, it must be when calculating the `ci` value?

**Comment by ipuzek** [comment]
I had checked that piece of code already, and I did not see the problem. The code seems to work as expected. "Normal" CIs are also OK.

However, relative CIs are way off, as far as I understand them. Have you tried running the example I wrote above? Is there maybe another piece of code that is changing something afterwards?

**Comment by sjPlot** [comment]
You're right, `total_sum` should be total sum of `mydat$frq` (which equals sample size). Fixed bug, relative ci's now look fine. Will commit tonight.
