### ISSUE TITLE
sjp.frq - error when values between 0 and 1

### ISSUE THREAD

**Issue by HoneyBuddha** [sjPlot/devel#125]
Hi, 

First, thank you for this incredible package!!

I wanted to alert you to a bug in sjp.frq. I am not sure if I am missing something, but the following two lines of code should reveal it to you. The only difference is whether the sample is from a normal with mean = 50 and sd =5 (works great) or mean = 0.50 and sd= 0.05 (doesnt work). I am guessing there might a default rounding? I cant seem to find a way to turn it off in the sjp.frq function. 

Please let me know if I can assist further with this bug. 

Thanks!

Works out of the box:
`sjp.frq(rnorm(10000,50,5), type = "hist", showValueLabels = FALSE, autoGroupAt = 5000, showNormalCurve = TRUE)`

Doesnt work:
`sjp.frq(rnorm(10000,0.50,0.05), type = "hist", showValueLabels = FALSE, autoGroupAt = 5000, showNormalCurve = TRUE)`

**Comment by sjPlot** [comment]
For histograms, don't use the `autoGroupAt` argument. Auto-grouping is done automatically. Simply adjust the bin-size with `geom-size`.
