### ISSUE TITLE
Random startup message to visit your website

### ISSUE THREAD

**Issue by svannoy** [sjPlot/devel#127]
Hi,

sjPlot is really awesome!

Just wondering why you have a message that shows up 20% of the time when the package is attached, that ignores the settings of verbose and quietly? 

Thanks
Steven

**Comment by sjPlot** [comment]
Didn't know about these options. How can I check whether user wants to prevent startup messages?

**Comment by svannoy** [comment]
Thanks for replying!

I’m not sure exactly, I’m only now starting to write a package, but what I do in my markdown files all the time is the following:

library(dplyr, warn.conflicts = FALSE, verbose=FALSE, quietly = TRUE)


Steven

*****************************
@stevenvannoy
https://stevenvannoy.wordpress.com

**Comment by sjPlot** [comment]
Ah ok, this, however, affects only other messages that are not directly printed from the package itself. However, you can use `suppressPackageStartupMessages(sjPlot)` to suppress this message in markdown files.

**Comment by svannoy** [comment]
Just for clarity, it needs to be `suppressPackageStartupMessages(library(sjPlot))` and that returns the name of the package even if echo=FALSE is set in the code segment so my current solution is:
`t <- suppressPackageStartupMessages(library(sjPlot))
rm(t)
`
I'm sure there's a better way to do that, but it works.

I spent several hours trying to figure out what was going on since you made this a random feature "zzz.R", then I had to understand a lot more about packages than I did before. Good learning experience but not a fun one.

**Comment by sjPlot** [comment]
Have you tried `message=FALSE` and `warning=FALSE`? I always use these arguments in the code block where I load libraries in a knitr-document.

**Comment by svannoy** [comment]
Aha, that’s a good one, I didn’t realize you could do that for the entire code block, much easier.

PS - any chance you’d code up an sj.aov? I wasn’t able to get sj.lm to work with an aov model output even though it seemed like it should. I use aov mostly for teaching (the students LOVE your package also).


Thanks
S

*****************************
@stevenvannoy
https://stevenvannoy.wordpress.com
