### ISSUE TITLE
Alternative Covariance Matrix

### ISSUE THREAD

**Issue by AndreWal** [sjPlot/devel#128]
Hi,

Thank you for providing this great package.

One Question, though. Would it be possible to provide an additional argument to the functions sjp.lm, sjp.glm, sjp.int etc. where users could add an alternative variance-covariance matrix that is used by the function instead of the variance-covariance matrix of the lm, glm etc. object?

Best, 
André

**Comment by sjPlot** [comment]
Which plot type do you exactly mean?

**Comment by AndreWal** [comment]
I have been working only with "eff" but I guess it would also make sense to implement it for "emm" since it allows to plot the CI.

**Comment by sjPlot** [comment]
Ok, I added a `...` for flebibly passing down arguments to the effects-function calls if `type = "eff"`. `type = "emm"` actually gives the same results as `type = "eff"` (i.e. effects- and lsmeans package give same results).
