### ISSUE TITLE
 "Error in `[.data.frame`(se.fit, , i) : undefined columns selected" when calling sjp.lmer(model, type="coef")

### ISSUE THREAD

**Issue by olivermueller** [sjPlot/devel#129]
I am trying to plot the joint random and fixed effects coefficients for each level of each grouping variable (actually, I am only interested in one grouping variable). I have three grouping vars with 948, 8, and 6 levels. Calling the function produces only one plot (for the grouping var with 948 levels) and the following errors and warnings:

> sjp.lmer(mlm3, type="coef")

Error in `[.data.frame`(se.fit, , i) : undefined columns selected

In addition: Warning messages:
1: In sweep(cmode.vars, 2, fixed.vars, "+") :
  STATS does not recycle exactly across MARGIN
2: In sweep(cmode.vars, 2, fixed.vars, "+") :
  STATS is longer than the extent of 'dim(x)[MARGIN]'
3: In sweep(cmode.vars, 2, fixed.vars, "+") :
  STATS does not recycle exactly across MARGIN
4: In sweep(cmode.vars, 2, fixed.vars, "+") :
  STATS does not recycle exactly across MARGIN
5: In sweep(cmode.vars, 2, fixed.vars, "+") :
  STATS is longer than the extent of 'dim(x)[MARGIN]'
6: In sweep(cmode.vars, 2, fixed.vars, "+") :
  STATS does not recycle exactly across MARGIN

**Comment by sjPlot** [comment]
Could you provide a reproducible example, or send me the RData file (including the data and fitted merMod object)?

**Comment by sjPlot** [comment]
Moved this issue to https://github.com/sjPlot/sjstats/issues/2, because it's an issue when computing the standard error for the CI. If you use the argument `show.ci = FALSE`, plotting works. I'll see whether I can fix this issue, because the function to compute the s.e. for mixed models comes from Ben Bolker and was only a quick solution.
