### ISSUE TITLE
sjp.glmer, how to change colour of predicted values  

### ISSUE THREAD

**Issue by JuliPluto** [sjPlot/devel#132]
Hi community,
I plotted a glmm with a binomial error structure with sjp.glmer().
The default output prints the predicted values as a blue line and I have been unable to customize the colour. Does somebody have an idea how to do that? 
geom.colors = c("") works with sjp.int() but not with sjp.glmer.
Thanks for your help!
Julian  

sjp.glmer(model, type = "fe.pc", vars=c(var1), geom.size = 0.7,
hideErrorBars = FALSE, showIntercept = TRUE,  
axisLimits.y = c(0.5,1),
facet.grid = FALSE, 
interceptLineType = 2,
showValueLabels = TRUE, 
labelDigits = 2, 
y.offset = 0.1,
show.ci = TRUE,
printPlot = TRUE)

**Comment by sjPlot** [comment]
fixed in current github version, works in the next update...
