### ISSUE TITLE
sjp.int(), rescale axis

### ISSUE THREAD

**Issue by JuliPluto** [sjPlot/devel#133]
Hi, 
is there a possibility to rescale the y axis when using sjp.int()? 
I plotted an interaction term from a glmm, the response variable is binomial. The tick marks on the y axes of the reulting plot are labled with % values from 0-100%. I would like to change that to decimals (0.0,0.2,...,1.0).
Anybody who could help me with that?
Thank you very much!
Julian

sjp.int(model, type = "eff", showCI = T, swapPredictors = T, valueLabel.digits = 2,
fillColor = "grey", fillAlpha = 0.3, 
geom.colors = c("grey30","grey30","grey30","grey30","grey30"),
geom.size = 0.7,  
moderatorValues="quart",
facet.grid = TRUE,
axisLimits.y=c(0.0,1.0),
printPlot = TRUE)

**Comment by sjPlot** [comment]
Use the return value (a ggplot-object) and then add another y-scale-layer. See example below:

```
library(sjmisc)
data(efc)
# create binary response
y <- ifelse(efc$neg_c_7 < median(stats::na.omit(efc$neg_c_7)), 0, 1)
# create data frame for fitted model
mydf <- data.frame(y = as.factor(y),
sex = as.factor(efc$c161sex),
barthel = as.numeric(efc$barthtot))
# fit model
fit <- glm(y ~ sex * barthel, data = mydf, family = binomial(link = "logit"))
# plot interaction, increase p-level sensivity
sjp.int(fit, type = "eff", legend.labels = get_labels(efc$c161sex), plevel = 0.1)

library(ggplot2)
sjp.int(fit, type = "eff", legend.labels = get_labels(efc$c161sex), plevel = 0.1)$plot.list[[1]] + scale_y_continuous()
```
