### ISSUE TITLE
sjt.lm does not work with pglm output

### ISSUE THREAD

**Issue by enricoforti** [sjPlot/devel#136]
Your package is great. I have been succefully using sjp.lm to plot the results of a pglm regression.

The sjt.lm() function does not seem to work with pglm regression tables. When using sjt.lm() I receive the following error:

sjt.lm(model1)

Error in terms.default(fit) : no terms component nor attribute
In addition: Warning message:
In if (class(input_list[[1]]) == "list") input_list <- lapply(input_list[[1]],  :
  the condition has length > 1 and only the first element will be used

**Comment by sjPlot** [comment]
In which package is the `pglm` function? Do you also have a reproducible example?

**Comment by helix123** [comment]
My guess is, its `pglm` from package `pglm` (panel generalized linear model)? Not sure about the status of the package because the last CRAN release was in 2013.

**Comment by sjPlot** [comment]
The  `pglm` function does not return an object of class **pglm**, as stated in the documentation. This makes it difficult to exactly identify pglm-models and support them in **sjPlot**.

You should also use `sjt.glm` to and `sjp.glm` to plot generalized linear models.

**Comment by sjPlot** [comment]
I just see that `pglm` objects do not support the generic `model.matrix` and `family` functions, so I can't provide proper support for these kind of models. Please contact the author of the pglm-package to address this issue.
