### ISSUE TITLE
show.na = "TRUE" is not available for frq but in stackfrq

### ISSUE THREAD

**Issue by kwcityhk** [sjPlot/devel#141]
The document said there is such an option to deal with missing values.  I ensure I download the latest version but still the help message does not prompt this as available.  I tried nevertheless.  Not work.

BTW, I noted that sjt.stackfrq got that parameter.  Just not sjt.frq.  ... :-(

For your kind attention.

Thanks.  (The package save my day and I can try other means.)

**Comment by sjPlot** [comment]
`sjt.frq` always prints missing values, as well as raw and valid percentages, so there is no need for such an option in `sjt.frq`.
