### ISSUE TITLE
Multiple side-by-side glmer forest plots

### ISSUE THREAD

**Issue by ashenkin** [sjPlot/devel#142]
Hi there,

trying to use sjp.glmm to plot multiple forest plots side-by-side, e.g.:

sjp.glmm(fit1, fit2, type = "fe")

however, getting the following error:
Error in exp(coef(fit)) : non-numeric argument to mathematical function

Any ideas?  These are binomial logit survival models.  Can pass along the models via email if helpful...  Tried sjp.glmer, but don't think that's built to handle multiple fits...

thanks,
alex

**Comment by sjPlot** [comment]
Hi Alex,
yes, please send me the models via email. I guess that the package used to fit the models do not provide all the necessary generic functions (`model.frame`, `coef` etc.) to access model attributes.

**Comment by sjPlot** [comment]
I'm not sure whether this meets your needs, but the latest update of sjPlot contains a `plot_grid()` function to arrange plots into a grid.
