### ISSUE TITLE
sjp.xtab empty categories problem

### ISSUE THREAD

**Issue by pegazpegaz** [sjPlot/devel#144]
Dear Dev,

I found, that when crossing variables (sjp.xtab, data loaded from .sav with `sjmisc::read_spss`) which got unused value labels (but no NA at crossing vectors) there's a problem with these unused value labels, which throws an error:

`Error in seq.default(lower_lim, upper_lim, by = grid.breaks) : 
  'to' cannot be NA, NaN or infinite`

I found that problem is setting `upper_lim` variable.
I think that changing line 165 in sjp.xtab
`upper_lim <- max(mydf$prc) * mlp`
to 
`upper_lim <- max(na.omit(mydf$prc)) * mlp`
does the thing.

Best regards,
Peter

**Comment by sjPlot** [comment]
Could you provide a reproducible example, so I can check whether your suggestions would fix the bug?

**Comment by pegazpegaz** [comment]
Here you go!

[SPSS.txt](https://github.com/sjPlot/devel/files/385655/SPSS.txt)
[R.txt](https://github.com/sjPlot/devel/files/385656/R.txt)

**Comment by sjPlot** [comment]
Thanks, bug fixed. Will commit update tonight.
