### ISSUE TITLE
sjt.lmer show.fstat not working

### ISSUE THREAD

**Issue by bpweitzm** [sjPlot/devel#146]
I'm working on a table output using sjt.lmer() and calling for show.fstat=TRUE to display F-statistics instead of pval.  After much manipulation I have been unsuccessful in creating a table showing F-stats.

**Comment by sjPlot** [comment]
`show.fstat` shows the F-statistics of the model, not for each coefficient. And it only applies to `sjt.lm`, not to `sjt.lmer`. I have fixed the documentation,

**Comment by bpweitzm** [comment]
Thanks for the clarification. How would I go about calling on the F-stats
by coefficient in lmer; or is this not possible/appropriate?

Thank you again.

**Comment by sjPlot** [comment]
The summary gives you a t-value for each coefficient - is it that what you are looking for?

**Comment by bpweitzm** [comment]
Yes, that is correct. How would I go about calling out into the HTML output
table?
