### ISSUE TITLE
sjp.lm with standartised coefficients bug?

### ISSUE THREAD

**Issue by bdemeshev** [sjPlot/devel#148]
This code
```
model <- lm(data = swiss, Fertility ~ Catholic + Agriculture + Examination)
sjp.lm(model, type = "std")
```
throws the error message `Error in order(tmp[["estimate"]]) : argument 1 is not a vector`

Am I wrong somewhere or it is a bug?

**Comment by sjPlot** [comment]
Yes, it's a bug introduced in the last update 2.0.2. I fixed this bug, however, can't commit right now. Update will follow the next days.
