### ISSUE TITLE
make sjt.int/sjt.lm/sjp.lm recognise plm's within (and random) estimator

### ISSUE THREAD

**Issue by helix123** [sjPlot/devel#15]
Just read that plm support has been added to sjt.int, great! It works for pooled OLS (pooling), but it does not seem to work for fixed effects ("within") nor random effects ("random").
    
    pooled <- plm(y ~ a + b + a:b, data=pdat, model="pooling")
    fe <- plm(y ~ a + b + a:b, data=pdat, model="within")
    re <- plm(y ~ a + b + a:b, data=pdat, model="random")

    sjp.int(pooled, plevel = 0.9) # works
    sjp.int(fe, plevel = 0.9) # Error: Predictors of interaction terms (main effects) must be included as single term as well. See Note in ?sjp.int 
[same for re]

Let me know if you need further input.

**Comment by helix123** [comment]
Uh, are plm models not supported by sjp.lm() and sjt.lm()?

````
sjp.lm(pooled) # works
sjp.lm(re)        # works
sjp.lm(fe)        #  does not work, probably due to fixed effects models having no intercept?
Error in if (!any(fit.labels == attr(fit$coefficients[i], "names"))) { : 
  missing value where TRUE/FALSE needed

````
For sjt.lm() I get:
````
sjt.lm(re) # and sjt.lm(pooled)
Error in nobs.default(input_list[[i]]) : no 'nobs' method is available

sjt.lm(fe)
Error in `$<-.data.frame`(`*tmp*`, "stdbv", value = c("", "0.09", "0.18",  : 
````
Would be great to have sjt.lm() support plm models!

**Comment by sjPlot** [comment]
Support for plm is not fully implemented yet - simply, because I have no experience with the plm package and have to figure out the exact differences to lm-objects.

**Comment by helix123** [comment]
There aren't so much differences; fixed effects models do not have an intercept (which would need a bit of attention if one prints a random or pooled OLS model (with intercept) next to a fixed effects model in a table.

When it comes to extracting coefficients and so on: Some columns have names slighltly different names compared to lm-objects. I found the package `broom` really handy to extract coefficient (`tidy(plm-object)`) and model statistics (`glance(plm-object)`) (also for a lot of other models!). If one wants to extract things out of plm models without an additional package, I wrote the specific column names here: https://github.com/dgrtwo/broom/issues/34 [maybe the source of broom has a "cleaner" implementation of the extraction).

Maybe a look at the source of `stargazer` package could be worthwile as well.

**Comment by sjPlot** [comment]
Which of these issues are still relevant? I have changed some code in between, so some issues may now be solved.

**Comment by helix123** [comment]
All of them, some with different or new errors. Missing `nobs` method has been added to `plm` in the meantime (at least in dev version: https://r-forge.r-project.org/R/?group_id=406, use that for testing, a lot has improved!)
Here is a reproducible example for all three model types:
````
library(plm)
data(Grunfeld, package = "plm")
form <- inv ~ value + capital + value:capital
pool <- plm(form, data = Grunfeld, model = "pooling")
fe   <- plm(form, data = Grunfeld, model = "within")
re   <- plm(form, data = Grunfeld, model = "random")

library(sjPlot)
sjp.int(pool, plevel = 0.9) # fails
sjp.int(fe, plevel = 0.9)    # fails
sjp.int(re, plevel = 0.9)    # fails
````
In principle, most things of the estimated models by `plm` should be equal to lm.

**Comment by sjPlot** [comment]
Ok, thanks, I'll look at it.

**Comment by sjPlot** [comment]
Update on what works for me now:

```
sjp.int(pool, plevel = 0.9) # works
sjp.int(fe, plevel = 0.9)    # fails
sjp.int(re, plevel = 0.9)    # works
```

**Comment by sjPlot** [comment]
```
sjt.lm(pool) # works
sjt.lm(fe)   # works
sjt.lm(re)   # works
```

Needs update of both **sjstats** and **sjPlot** package.
For model `fe` in `sjp.int`, I need some further investigation.
