### ISSUE TITLE
how does sjt.lmer calculate the confidence intervals?

### ISSUE THREAD

**Issue by turquoisesquid** [sjPlot/devel#151]
It seems like an obvious question, but I can't find this information anywhere, not even in the sjt.lmer documentation.

Thanks a lot for any hints!

**Comment by sjPlot** [comment]
It depends. When you fit your model with `lmerTest::lmer`, then the p-value as returned by the `summary()` function is used, which should be the p-value based on the t-statistics with Satterswaithe-approximation for the df.

When you fit your model with `lme4::lmer`, and set the argument `p.kr = TRUE`, then it's the p-value based on t-statistics with Kenward-Rogers-approximation for the df.

Else, the t-statistics is used and treated as Wald z, so a normal-distribution is assumed. 

You can find the details here:
https://github.com/sjPlot/sjstats/blob/master/R/merMod_p.R#L35

In the next update of my **sjstats**-package, there will be a generic `get_model_pval()`-function for different kind of models, such as lm, glm, lmer, glmer, gls or pggls. See https://github.com/sjPlot/sjstats/blob/master/R/merMod_p.R#L108

**Comment by sjPlot** [comment]
Sorry, the question was about CI, not p-values... 
I simply used the `confint.merMod()`-method from the **lme4**-package, but I revised the `sjt.lmer()`-function - it now uses `broom::tidy()`, which internally also calls the confint-method from lme4.

https://github.com/sjPlot/devel/blob/master/R/sjTabLinReg.R#L452
