### ISSUE TITLE
margins and coef names in sjp.lmer coefficient plot

### ISSUE THREAD

**Issue by eborbath** [sjPlot/devel#153]
I am using 
```
sjp.lmer(test1, type = "fe", sort = TRUE,
         title = NULL,
         geom.colors = c("black", "black"))
```
to generate a fixed effects coefficient plot of a hierarchical linear probability model. I have two issues, which I could not figure out:

1. is it possible to change the margins of the coef labels, since by default they overlap with the confidence interval bars..? I tried several options with sjp.setTheme but could not find the one I needed.

2. is it possible to edit the variable names on the Y axis? I would not use the ones in the dataset for presenting the results.

Thanks and sorry if I am overlooking something in the documentation.

**Comment by sjPlot** [comment]
According to 1), do you mean the values annotated to the points? If so, try the argument `y.offset`.

To 2), use the `axis.labels`-argument.

**Comment by eborbath** [comment]
Thank you! Both solutions worked.
The only thing I still could not figure out is how to get rid of the title. The option `title = NULL` does not takes it off.

**Comment by sjPlot** [comment]
`title = ""`
