### ISSUE TITLE
sj.glm

### ISSUE THREAD

**Issue by atuofa** [sjPlot/devel#155]
i am interested in plotting predicted probabilities using the sjp.glm function and type = "slope". The default color for prediction lines is RED. Please, is there a code to change this color to BLACK. I have tried geom.color = "black" but it did not work for me. 
Thank you

**Comment by sjPlot** [comment]
for me, `sjp.glm(fit, type = "slope", geom.colors = "black")` works fine. Wich package version have you installed?
