### ISSUE TITLE
Suggestion: Numericals in sjt.frq

### ISSUE THREAD

**Issue by methodds** [sjPlot/devel#158]
Hi, 

first of all thank you for this awesome package! I have a suggestion for the frequency tables: Could you include an option, where besides each value label, the corresponding numerical is also listed? This would be very handy for survey researchers, so that the table can be used for a combined overview of labels and numericals.
It would be equivalent to the  standard output of SPSS ```FREQUENCIES``` while looking much nicer ;):

![image](https://cloud.githubusercontent.com/assets/7460499/20216884/560ddb2c-a81d-11e6-9b08-0acc8f742d30.png)

**Comment by sjPlot** [comment]
If you use labelled data, you can use `sjmisc::to_label()` as workaround:

```
library(sjmisc)
library(sjPlot)
data(efc)
sjt.frq(to_label(efc$e15relat, prefix = TRUE))
```

for a quick glance, you could also use `sjmisc::frq()`:

```
frq(efc$e42dep)
```

Is this sufficient enough for you?

**Comment by sjPlot** [comment]
You can also use it in a pipe-flow:

```
library(dplyr)
efc %>% 
  select(e42dep, e16sex, e15relat) %>% 
  to_label(prefix = T) %>% 
  sjt.frq()
´´´

**Comment by methodds** [comment]
``frq() is perfect, just what I needed. Thank you :)

**Comment by sjPlot** [comment]
And you could also wrap that data frame into a html-table:

```
f <- frq(efc$e42dep)
sjt.df(f[[1]], describe = F, show.rownames = F, CSS = list(css.centeralign = "text-align:left;"))
```
