### ISSUE TITLE
probemod package

### ISSUE THREAD

**Issue by helix123** [sjPlot/devel#16]
You might want to have a look at the probemod package for printing (and calculation) of (among other) the Jason Neyman method for significant parts of the interaction. Plot is not as pretty as sjt.int's, though.

**Comment by sjPlot** [comment]
Closed, because not a real "issue", more a pm. Nevertheless, I'll take a look at the suggested package, thanks for the hint!

**Comment by sjPlot** [comment]
The `probemod` package seems to be buggy, throws many errors when testing it.

    library(sjmisc)
    data(efc)
    mydf <- data.frame(burden = efc$neg_c_7, sex = efc$c161sex, education = efc$c172code, barthel = efc$barthtot)
    fit <- lm(burden ~ .*., data = mydf)
    summary(fit)

Summary:

    Coefficients:
                       Estimate Std. Error t value Pr(>|t|)    
    (Intercept)       13.537239   2.348700   5.764 1.17e-08 ***
    sex                1.128579   1.159273   0.974   0.3306    
    education         -0.316583   0.910718  -0.348   0.7282    
    barthel           -0.049160   0.024337  -2.020   0.0437 *  
    sex:education      0.113275   0.443998   0.255   0.7987    
    sex:barthel       -0.010938   0.010152  -1.077   0.2816    
    education:barthel  0.007555   0.007016   1.077   0.2819    
    ---
    Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1


    library(pobemod)
    jnresults <- jn(fit, dv='burden', iv='sex', mod='education')
    Warnmeldungen:
    1: In sqrt(jnb^2 - 4 * jna * jnc) : NaNs wurden erzeugt
    2: In sqrt(jnb^2 - 4 * jna * jnc) : NaNs wurden erzeugt
    plot(jnresults)
    Values of education indicated by the shaded region
                   x   y yse   t   p
    Lower Bound: NaN NaN NaN NaN NaN
    Upper Bound: NaN NaN NaN NaN NaN
    Fehler in 1:nrow(x$signintervals) : Argument der Länge 0
