### ISSUE TITLE
efc Data Not Found

### ISSUE THREAD

**Issue by wushengzhong** [sjPlot/devel#161]
I cannot locate **efc** dataset after I installed and loaded sjPlot package. Not sure if it's gone forver.
`install.packages("sjPlot")`
`library(sjPlot)`
`data(efc)`

<img width="397" alt="screen shot 2016-11-22 at 11 13 52 pm" src="https://cloud.githubusercontent.com/assets/8701128/20553421/697517e4-b109-11e6-9c1d-1f20fa6914ca.png">

**Comment by sjPlot** [comment]
the data set is in the _sjmisc_ or _sjstats_ package, which are both installed with the _sjPlot_ package. So load on of the two libraries first.
