### ISSUE TITLE
sjp.likert - negative categories mixed-up

### ISSUE THREAD

**Issue by JaromirCZE** [sjPlot/devel#164]
Hi and thank you for this amazing package! My issue is with sjp.likert. The same code I already used in the past with success behaves strange now: It returns funny ordering of the negative (left) part of the scale, specifically, it puts the most negative category right to the 0 axis and the least negative quite to the left. So basically it returns the negative side of the scale in reverse order. 

See the picture below for what I mean.

![image](https://cloud.githubusercontent.com/assets/6377556/20721034/bb610768-b661-11e6-802c-6b685d269f74.png)

For this picture, I used your example code:

# prepare data for 6-category likert scale, 5 items
likert_6 <- data.frame()

Q1 <- as.factor(sample(1:6, 500, replace = TRUE, prob = c(0.2,0.1,0.1,0.3,0.2,0.1)))
Q2 <- as.factor(sample(1:6, 500, replace = TRUE, prob = c(0.15,0.15,0.3,0.1,0.1,0.2)))
Q3 <- as.factor(sample(1:6, 500, replace = TRUE, prob = c(0.2,0.25,0.05,0.2,0.2,0.2)))
Q4 <- as.factor(sample(1:6, 500, replace = TRUE, prob = c(0.2,0.1,0.1,0.4,0.1,0.1)))
Q5 <- as.factor(sample(1:6, 500, replace = TRUE, prob = c(0.1,0.4,0.1,0.3,0.05,0.15)))

likert_6 <- data.frame(Q1, Q2, Q3, Q4, Q5)

# create labels
levels_6 <- c("Very strongly agree", "Strongly agree", "Agree",
              "Disagree", "Strongly disagree", "Very strongly disagree")

# create item labels
items <- c("Q1", "Q2", "Q3", "Q4", "Q5")

# plot 6-category-likert-scale, ordered by positive values,
# in brown color scale
sjp.likert(likert_6,  legend.labels = levels_6, axis.labels = items, 
           sort.frq = "pos.asc", digits = 0, show.prc.sign = TRUE,
           values = "sum.inside")

**Comment by SamJLynch** [comment]
Hi,

I'm experiencing the same problem.  I'm on version 2.1.2 of sjPlot, has this issue been resolved in that version?

Thanks

Sam

**Comment by sjPlot** [comment]
No, it's part of the forthcoming update, see https://github.com/sjPlot/devel/blob/master/NEWS.md
If you like to install the GitHub-version, make sure to install sjmisc (https://github.com/sjPlot/sjmisc) first, because one bug fix in sjPlot depends on new functions in sjmisc.
