### ISSUE TITLE
sjt.xtab Output getting displayed in viewer pane only and not in Shiny app

### ISSUE THREAD

**Issue by Dev1412** [sjPlot/devel#165]
I am generating a cross table output (contingency table). My requirement is to have column percentages along with row and column totals. I found this package "sjPlot" which gives very good output with colour features and was meeting my requirement. I used this package to generate the output in Shiny. But to my surprise the output is getting generated only in the viewer pane and not in the app. Below is a small part of my code.

    library("shiny")
    library("sjPlot")
    
    ui <- shinyUI(fluidPage(
      tabPanel("First Page"),
      mainPanel(tabsetPanel(id='mytabs',
                            tabPanel("Table",tags$b(tags$br("Table Summary" )),tags$br(),dataTableOutput("crosstab2"))
                            )
                )
      ))
    
    
    server <- shinyServer(function(input, output,session){
      updateTabsetPanel(session = session
                        ,inputId = 'myTabs')
      
      output$crosstab2 <- renderDataTable({
          with(mtcars,sjt.xtab(mpg, cyl,
                            var.labels = c("mpg","cyl"),
                            show.col.prc = T,
                            show.summary = F,
                            show.na = F,
                            wrap.labels = 50,
                            tdcol.col = "#f90477",
                            emph.total = T,
                            emph.color = "#3aaee0",
                            CSS = list(css.table = "border: 1px solid;",
                                       css.tdata = "border: 1px solid;")))      
        })
        
        print("created crosstab1")    
    })
    
    shinyApp(ui = ui, server = server)
    
    

This generates the needed output in viewer pane. How can I get this output displayed in the app. I can not save this output as a image as in my actual program the variables are getting selected dynamically and the table output accordingly changes.

**Comment by sjPlot** [comment]
I'm not very familiar with shiny, so I'm afraid you may need to ask at stackoverflow to find a solution. You can use the arguments `file`, `use.viewer` and `no.output` to manipulate where the table-file is written to or displayed (see `?sjt.xtab`). 

The table-functions all produce HTML-pages - if you can integrate those into Shiny, you could use the return-value of the `sjt.xtab()`-function. You might find some help here: http://strengejacke.de/sjPlot/sjtbasics/

**Comment by Dev1412** [comment]
Oh, I have posted on stackoverflow as well yesterday and still waiting for a response. The output tables are quite beautiful and displaying them in Shiny app makes it better. I have managed to get the html table in Shiny with some r & d by using includeHTML function.....but by app updates tables dynamically and the html is not getting updated for next set of variables......hope some one would have some solution to access the table from the viewer pane and render the ouputs dynamically...

**Comment by sjPlot** [comment]
Seems to be solved:
http://stackoverflow.com/q/40991183/2094622

**Comment by Dev1412** [comment]
Yes, Thank you for closing !!
