### ISSUE TITLE
Suggestion: Enable one import for al sj packages

### ISSUE THREAD

**Issue by methodds** [sjPlot/devel#167]
I would suggest to enable a shortcut for importing all the nice ```sj``` packages in one line,
e.g. ``library(sjtools)``. This would be similar to [tidyverse](https://github.com/tidyverse/tidyverse) and just safe time/code as usually one  ends up importing all of the packages anyway.

**Comment by sjPlot** [comment]
https://github.com/sjPlot/strengejacke

**Comment by methodds** [comment]
Oh I'm sry, didn't find this repo yet. Thanks anyway :)

**Comment by methodds** [comment]
Wait is ````strengejacke```` already on ```CRAN```?

**Comment by sjPlot** [comment]
No, it is just a GitHub-repo, because I find this package does too less to "waste" CRAN members' resources by submitting this package.
