### ISSUE TITLE
sjp.likert output issues for neutral category

### ISSUE THREAD

**Issue by methodds** [sjPlot/devel#168]
Hi,

when trying to use ``sjp.likert()`` for items with a neutral category, the labels, digits and colors are not displayed properly:

![sjp_likert](https://cloud.githubusercontent.com/assets/7460499/21025897/96c904de-bd8a-11e6-9928-6df2019e488b.png)

```
library(tidyverse)
library(sjPlot)
library(sjmisc)

d <- read_stata('Allbus_2014_PolSoz.dta')
zuw <- find_var(d,  'zuwanderer')
d[, zuw] %>%  set_na(c(6,8,9)) %>% sjp.likert(catcount=4,cat.neutral=3)


```
The dataset for reproduction purposes is available [here](https://www.dropbox.com/s/qp7ablx3f9r3w8e/Allbus_2014_PolSoz.dta?dl=1).

By the way: Is it possible to switch the angle for the percentage digits, such that they are for example displayed vertically? This might solve display issues for categories which are only observed very few times.

**Comment by sjPlot** [comment]
Thanks, fixed. The label position was already fixed in the current GitHub-snapshot, however, the legend labels were not correctly sorted, which is fixed now.

Label angel can be adjusted with `sejp.setTheme()` resp. `set_theme()`.

```
d <- read_stata('Allbus_2014_PolSoz.dta')
zuw <- find_var(d,  'zuwanderer')
sjp.setTheme(geom.label.angle = 90)
d[, zuw] %>%  set_na(c(6,8,9)) %>% sjp.likert(cat.neutral = 3)
```

**Comment by methodds** [comment]
thanks :)
