### ISSUE TITLE
calculation of fitted values in sjp.int()

### ISSUE THREAD

**Issue by helix123** [sjPlot/devel#17]
Could you check if sjp.int( , moderatorValue="minmax") calculates correctly?
Just checked the plots with the dataset in Hayes (2013), p. 232 [dataset protest is available at http://afhayes.com/introduction-to-mediation-moderation-and-conditional-process-analysis.html], however, I think you can follow without this specific dataset.
I have:
   
 head(protest)
Source: local data frame [6 x 4]

  sexism liking respappr protest
1   4.87   4.83     4.25       1
2   4.25   4.50     5.75       0
3   5.00   5.50     4.75       1
4   5.50   5.66     7.00       1
5   5.62   6.16     6.75       1
6   5.75   6.00     5.50       1

 h3 <- lm(liking ~ protest + sexism + protest:sexism,    data=protest)
h3
Call:
lm(formula = liking ~ protest + sexism + protest:sexism, data = protest)

Coefficients:
   (Intercept)         protest          sexism  protest:sexism  
        7.7062         -3.7727         -0.4725          0.8336  

   # this should replicate the minmax calculation of sjp.int()
    pro2 <- c(0,1,0,1)
    sex2 <- c(rep(min(protest$sex), 2), rep(max(protest$sexism), 2))
    df2 <- data.frame(protest=pro2, sexism=sex2)
    df2 <- cbind(df2, pred = predict(h3, df2))

df2
  protest sexism     pred
1       0   2.87 6.350185
2       1   2.87 4.969828
3       0   7.00 4.398798
4       1   7.00 6.461013

compare the predicted (fitted) values to sjp.int's plot; sjp.int's maximum values seem to be off. The lines should cross each other at a value of sexim (moderator) of slightly above 4.5

sjp.int(h3, moderatorValue="minmax", showValueLabels = TRUE)

![rplot](https://cloud.githubusercontent.com/assets/10897278/6993439/2ad0f224-daf5-11e4-98ef-13d6abb376ae.png)

**Comment by helix123** [comment]
please also check moderatorValue="meansd", if the above comment applies.

**Comment by sjPlot** [comment]
I simply use following formulae:

    miny <- (b0 + (b1 * pred1uniquevals) + (b3 * pred1uniquevals * ymin))
    maxy <- (b0 + (b1 * pred1uniquevals) + (b3 * pred1uniquevals * ymax))

as shown in these two postings
http://www.theanalysisfactor.com/interpreting-interactions-in-regression/
http://www.theanalysisfactor.com/clarifications-on-interpreting-interactions-in-regression/

The value `b0`, `b1` and `b3` are the estimated coefficients, the `pred1uniquevalues` is the value range from the predictor at the x-axis (retrieved from the `model.matrix`) and `ymin` and `ymax` are the min/max values of the second predictor (moderator, which is indicated in the legend).

For your example, it would be:

    (Intercept) + (estimate_protest) * protest$protest + (estimate_protest:sexims) * protest$protest * min/max_protest$sexism

I'm not sure, whether `predict` captures the interaction effect?

**Comment by helix123** [comment]
Thanks for your answer.
Using your formulae and these estimates
(Intercept)         protest          sexism  protest:sexism  
        7.71         -3.77           -0.47           0.833  
and min|max protest = 0|1; min|max sexism = 2.87|7
that would yield
> 7.71 + -3.77 * 0 + (0.833 * 0 * 2.87)
[1] 7.71
> 7.71 + -3.77 * 1 + (0.833 * 1 * 2.87)
[1] 6.33071
> 7.71 + -3.77 * 0 + (0.833 * 0 * 7)
[1] 7.71
> 7.71 + -3.77 * 1 + (0.833 * 1 * 7)
[1] 9.771

I am not sure whether b2 should be in the posted formulae? In the code I see (b1 is not used there):
      est_b <- b1 + b0
      for (j in 1:length(pred2uniquevals)) {
        pr <- pred2uniquevals[j]
        miny <- (b0 + (b2 * pr) + (b3 * pr * ymin))
        maxy <- (b0 + (b2 * pr) + (b3 * pr * ymax))

Also I cannot find how that is related to the blog posts?
I found Height = 35 + 4.2*Bacteria + 9*Sun + 3.2*Bacteria*Sun and formulae for the conditional effects.

**Comment by helix123** [comment]
Thanks for your answer.
Using your formulae and these estimates
(Intercept)         protest          sexism  protest:sexism  
        7.71         -3.77           -0.47           0.833  
and min|max protest = 0|1; min|max sexism = 2.87|7
that would yield
> 7.71 + -3.77 * 0 + (0.833 * 0 * 2.87)
[1] 7.71
> 7.71 + -3.77 * 1 + (0.833 * 1 * 2.87)
[1] 6.33071
> 7.71 + -3.77 * 0 + (0.833 * 0 * 7)
[1] 7.71
> 7.71 + -3.77 * 1 + (0.833 * 1 * 7)
[1] 9.771

I am not sure whether b2 should be in the posted formulae? In the code I see (b1 is not used there):
      est_b <- b1 + b0
      for (j in 1:length(pred2uniquevals)) {
        pr <- pred2uniquevals[j]
        miny <- (b0 + (b2 * pr) + (b3 * pr * ymin))
        maxy <- (b0 + (b2 * pr) + (b3 * pr * ymax))

Also I cannot find how that is related to the blog posts?
I found Height = 35 + 4.2*Bacteria + 9*Sun + 3.2*Bacteria*Sun and formulae for the conditional effects.

**Comment by helix123** [comment]
I just check with the package "effects":

protest$protest <- factor(protest$protest) # need to convert to factor before

allEffects(h3)
 model: liking ~ protest + sexism + protest:sexism

 protest*sexism effect
       sexism
protest        3        4        5        6        7
      0 6.288761 5.816270 5.343779 4.871288 4.398798
      1 5.016766 5.377828 5.738889 6.099951 6.461013

And the plot as given by plot(allEffects(h3)) 
![rplot01](https://cloud.githubusercontent.com/assets/10897278/7003894/3b050748-dc62-11e4-9377-4f8b2c49b8b4.png)

**Comment by sjPlot** [comment]
> I am not sure whether b2 should be in the posted formulae? In the code I see (b1 is not used there):
> est_b <- b1 + b0
> for (j in 1:length(pred2uniquevals)) {
> pr <- pred2uniquevals[j]
> miny <- (b0 + (b2 * pr) + (b3 * pr * ymin))
> maxy <- (b0 + (b2 * pr) + (b3 * pr * ymax))
> Also I cannot find how that is related to the blog posts?
> I found Height = 35 + 4.2 * Bacteria + 9 * Sun + 3.2 * Bacteria * Sun and formulae for the conditional > effects.

See this 2nd posting:
http://www.theanalysisfactor.com/clarifications-on-interpreting-interactions-in-regression/

As far as I understood, the single estimate of the moderating variable is not needed to explain the effect of the moderator on a predictor. Only the predictor's estimate + interaction_estimate is needed to explain the effect of the moderation.

While the line with protest = 0 in the effects-plot seems to be identical to the result of `sjp.int`, I can't figure out how the effects of protest = 1 are computed?

Here is what `allEffects` prints:

    protest*sexism effect
           sexism
    protest        3        4        5        6        7
          0 6.288761 5.816270 5.343779 4.871288 4.398798
          1 5.016766 5.377828 5.738889 6.099951 6.461013

and here are the model's coefficients:

    Coefficients:
                    Estimate Std. Error t value Pr(>|t|)    
    (Intercept)       7.7062     1.0449   7.375 1.99e-11 ***
    protest1         -3.7727     1.2541  -3.008  0.00318 ** 
    sexism           -0.4725     0.2038  -2.318  0.02205 *  
    protest1:sexism   0.8336     0.2436   3.422  0.00084 ***

How do you compute the values in the 2nd row of allEffects?

**Comment by helix123** [comment]
2nd line is just plugging in values into the regression line:
protest = 1; sexism=3 yields 7.7 + -3.77 * 1 + -0.47 * 3 + 0.83 * 1 * 3 = 5.01

the difference is the marginal effect of a predictor and the overall outcome of the dependend variable which I think you have calculated. I really like Hayes (2013) book as it has a gentle introduction. You can also have a look at Brambor et al. (2006), Understanding Interaction Models: Improving Empirical Analysis, in: Political Analysis, 63-82. with a concise treatment, see esp. p. 71 for the marginal effect and unconditional effect

**Comment by sjPlot** [comment]
Ok, I had a typo when I tried the formulae you posted. Perhaps I add an option to plot both, the marginal and the overall outcome.

**Comment by helix123** [comment]
Would love to see the overall outcome implemented. 

For the marginal effect:
For those formulae you have now in the package, I believe, they just take care of the case then the other predictor is zero. Assuming zero does not need to make much sense, e.g. when zero is no possible value for the predictor (empically). Often, one assumes the mean instead of zero (and +/- 1 sd in separate lines) - is that what `moderatorValues="meansd"` is supposed to do?

Have a look `effect()` which give the marginal effect of sexism with protest set to it's mean (and mean for all other covariates, if any)
````
effect("sexsim", model)

 sexism effect
sexism
       3        4        5        6        7 
5.421043 5.517177 5.613312 5.709446 5.805580
````
To calculate the value for e.g. sexism==3:
`7.7 + -3.7727 * 0.682 + -0.4725 * 3 + 0.8336 * 3 * 0.682 == 5.415064`

`plot(effect("sexism", model))`

Given that, should there be the upper line at all in
`sjp.int(model, moderatorValue="minmax", showValueLabels = TRUE)`?
````
10.2 != 7.7 + -3.7727 * 1 + -0.4725 * 7 + 0.8336 * 1 * 7 == 6.455
10.2 == 7.7 + -3.7727 * 0 + -0.4725 * 7 + 0.8336 * 1 * 7
````
Shouldn't the last 1 be 0 instead? Thus, no two lines in the plot, but just one?

**Comment by sjPlot** [comment]
The effects-package, in models with multipel co-variates, remaining co-variates are set to the mean when computing the interaction effect. E.g.,

    fit <- lm(formula = usage ~ burden + sex + dependency * education, data = mydf)
    summary(fit)
    (Intercept)            0.019659340
    burden                 0.028296046
    sex1                   0.009444551
    dependency             0.130328980
    education2             0.318471052
    education3            -0.658832300
    dependency:education2 -0.019582172
    dependency:education3  0.375478198

So, `allEffects` computes, for the interaction of dependency and education, 

    0.0196 + mean(burden) * 0.0282... + mean(sex1) * 0.00944... + dependency * 0.1303... + education3 * -0.6588... + dependency:education3 * 0.375478

while `sjp.int` just calculates

    0.0196 + dependency * 0.1303... + dependency:education3 * 0.375478

or 

    0.0196 + education3 * -0.6588... + dependency:education3 * 0.375478

(depending on whether you want to look at the effect of education on dependency or the effect of dependency on education)

`mean(burden)` and `mean(sex1)` only affect the overall "intercept", while including both `dependency * 0.1303...` and `education3 * -0.6588...` also affect the slope.

If I understood right, the first example from the `effects` package calculates the *marginal effects* (see also https://www3.nd.edu/~rwilliam/stats/Margins01.pdf, slide 22f)? While my approach in `sjp.int` just shows the moderating effect, independent from the overall mean? (if yes, how is this called?)

**Comment by sjPlot** [comment]
I added a `type` parameter to `sjp.int` to plot different types of interactions, thereby integrating former `sjp.emm.int` into `sjp.int`. Since it becomes difficult to calculate effects when models contain multiple interaction terms, I simply use the `effects` package to calculate effects with `type = "eff"` - why re-inventing the wheel?

    library(sjPlot)
    sjp.setTheme(theme = "539")
    sjp.int(h3, type = "eff", showCI = T)

![rplot1](https://cloud.githubusercontent.com/assets/4901179/7094687/dd29a074-dfc3-11e4-9655-b2e4bfc46073.png)

    sjp.int(h3, type = "eff", showCI = T, facet.grid = T)

![rplot2](https://cloud.githubusercontent.com/assets/4901179/7094690/e2914328-dfc3-11e4-98d5-326fbbb00596.png)

**Comment by sjPlot** [comment]
Ok, `type = "eff"` displays effects-plots calculated by `effects`-package, and `type = "cond"` plots conditional effects (the former default of `sjp.int`), as described [in Hayes 2012, p4](http://www.personal.psu.edu/jxb14/M554/articles/process2012.pdf). Will commit the changes this evening.

**Comment by helix123** [comment]
Sorry, haven't had time to follow your posts lately but will do so in a few days (I hope). Great to see those things implemented!

Just a short question about the naming of the `type` parameter (haven't got the time to think it through properly, so please handle with care):
Isn't it both conditional effects (`eff` and `cond`) while the difference is what the other covariates are set to? 
`eff`: other covariates set to their mean; `cond`: coveriates set to 0.
Thus, the result of some regression w/o any additional covariates with the effects package should be the same as with `type=cond`? If so, does it make sense to refer to value of covariates in the parameter? E. g. `type=covar_mean` and `type=covar_zero`

**Comment by sjPlot** [comment]
See Hayes 2012, p4: `b1*x + b3 * x * m` is the conditional effect (resp. `b1 + b3 * m`).

**Comment by sjPlot** [comment]
Could not access github, so a bit late my addition... If I understood Hayes right, the key message is:

> It estimates how much two cases that differ by one unit on X are estimated to differ on Y when M equals some specific value. This expression for the conditional effect of X also clarifies the interpretation of c1 and c3 in equations 1 and 2; c1 estimates the effect of X on Y when M=0, and c3 estimates how much the effect of X on Y changes as M changes by one unit.

with the formula: Y = (c1 + c3 * M) * X + c2 * M + e

So, `c2 * M` is excluded from calculating the difference on Y. The `effects` package would include this coefficient (main effect of moderation) as well, thus the slope would be slightly different.

This is, what Hayes calls _conditional effect_ or _simple slope_ - and this is, what `sjp.int` was doing until package version 1.7. I'm not sure, whether the effects calculated by the `effects` package may be called _marginal effects_, so the type-parameter could be either `type = "cond"` or `type = "marg"` or so...
