### ISSUE TITLE
sjt.xtab does not work at all

### ISSUE THREAD

**Issue by northwardRM** [sjPlot/devel#170]
Just running a simple sjt.xtab gives me:

>sjt.xtab (mydataset$gender, mydataset$categoricalage)

>Error: 'table_values' is not an exported object from 'namespace:sjmisc'

I obviously also have sjmisc installed and up to date

**Comment by sjPlot** [comment]
I guess you are using an old version of sjPlot.

**Comment by sjPlot** [comment]
Changing namespace from sjmisc to sjstats was already done back in May (https://github.com/sjPlot/devel/commit/103c336859b9323747083e2df65602d64fe00fe8), so you're pretty certainly not using the latest sjPlot-version.
