### ISSUE TITLE
Error for sjt.grpmean

### ISSUE THREAD

**Issue by methodds** [sjPlot/devel#171]
Hi,

trying to use ``sjt.grpmean()`` for two variables throws the following error:

`````
sjt.grpmean(vars$q40a, vars$q11bb)


Error in `row.names<-.data.frame`(`*tmp*`, value = value) : invalid 'row.names' length
5. stop("invalid 'row.names' length")
4. `row.names<-.data.frame`(`*tmp*`, value = value)
3. `row.names<-`(`*tmp*`, value = value)
2. `rownames<-`(`*tmp*`, value = c("-82. keine andere Partei waehlen", "-81. noch nicht entschieden", "-72. nicht einzuschaetzen", "-71. nicht bekannt", "1. CDU/CSU", "2. CDU", "3. CSU", "4. SPD", "5. FDP", "6. GRUENE", "7. DIE LINKE", "101. 50PLUS", "102. AB", "103. AB 2000", "104. ABS", ...
1. sjt.grpmean(vars$q40a, vars$q11bb)

`````
A dataset for reproduction is available [here](https://dl.dropboxusercontent.com/u/22352379/grpmean_error.RData).

**Comment by sjPlot** [comment]
but requires the latest GitHub-commit of _sjmisc_.

**Comment by sjPlot** [comment]
The tagged NA structure of that data set was somewhat messy - was it a Stata data file?

**Comment by methodds** [comment]
Yep, its from the Stata file that I linked in [this issue](https://github.com/sjPlot/sjmisc/issues/32#issuecomment-266274006).
