### ISSUE TITLE
Suggestion:  intr.var for sjt.grpmean()

### ISSUE THREAD

**Issue by methodds** [sjPlot/devel#172]
Hi, 

it would be nice to have an option for grouping by a third variable in ``sjt.grpmean()`` similar to ``intr.var`` in ``sjp.grpfrq()``.

At the moment I'm trying to work around this by using ``filter`` from dplr, which does however raise an error:

```
data(efc)
efc %>% filter(e16sex==1) %>%  sjt.grpmean(c12hour, e42dep)
efc %>% filter(e16sex==2) %>%  sjt.grpmean(c12hour, e42dep)


Error in sjmisc::get_labels(var.grp, attr.only = F, include.values = NULL, : object 'c12hour' not found
```
I guess the function is not yet compatible with pipes? Would it have to accept a dataframe as first input?

**Comment by sjPlot** [comment]
You can use `sjtab()`:

```
data(efc)
efc %>% filter(e16sex==1) %>%  sjtab(c12hour, e42dep, fun = "grpmean")
```

I'm not sure if I will add support for interaction term soon, as it can easily done with filtering and I guess I will work on other issues first - I definitely need more time ;-)

**Comment by methodds** [comment]
Ah cool I didn't know how to use ``sjtab()``, thats works just fine.  Thanks :)

**Comment by sjPlot** [comment]
I'll close this issue here, because I'm probably including support for grouped data frames in `sjplot` and `sjtab`.
