### ISSUE TITLE
Inheritance of parameters

### ISSUE THREAD

**Issue by methodds** [sjPlot/devel#174]
Hi,
I'm not sure how easy this is in ``R`` but from what I understand higher level functions like ``sjp.lm()`` rely on lower level functions like ``sjp.scatter()`` right? It would be pretty nice if they would then also be able to inherit corresponding parameters. 
As an example, when using ``sjp.lm()`` one might want a scatter plot to be included but without jittering. At the moment neither ``auto.jitter=F`` nor ``jitter.dots=F`` have any effect if used within ``sjp.lm()``. There are probably maaany more examples for other funtctions where inheritance could also be useful.

Anyway, it seems like I should stop bombarding you with suggestions and rather learn how your packages work at a low level so that I can start contributing ;-)

**Comment by sjPlot** [comment]
> I'm not sure how easy this is in R but from what I understand higher level functions like sjp.lm() rely on lower level functions like sjp.scatter() right? 

No. Functions share common code to avoid redundant code snippets, but when data points (as scatter plot) are added to outputs from, say, `sjp.lm()` or `sjp.glm()`, this is completely independent from the `sjp.scatter()`-function. So, a way of inheriting arguments like you suggested is not possible in this way, but would require re-writing certain parts of the code.

**Comment by methodds** [comment]
Ah I see, thanks for the explanation. I guess this issue can be closed then.
