### ISSUE TITLE
t-tests for categorical variable vs numerical variable? 

### ISSUE THREAD

**Issue by sdesai90** [sjPlot/devel#176]
Hello,

Firstly, great job on this package, it is awesome! 

I was wondering if there is a function in this package which allows t-tests  (i.e. Grouped variable vs numerical variable) to be shown in table? I see chi squared tests for contignency tables which is good for two categorical variables but is there anything for t-tests? 

Thanks,

**Comment by sjPlot** [comment]
In `sjt.grpmean()`, there's an F-test statistics (it's a simple one-way-anova table). What would you expect from such a function? Which kind of plot or table output?
