### ISSUE TITLE
Suggestion: Option for another CI style

### ISSUE THREAD

**Issue by methodds** [sjPlot/devel#177]
Hi,
social scientists often use quasimetric attributes (e.g. with 7 likert style categories) in their models. I would like to suggest adding an option for a different confidence interval theme for ``sjPlots``.
At the moment CI's look like this:
```

library(sjmisc)
data(efc)
# create binary response
y <- ifelse(efc$neg_c_7 < median(na.omit(efc$neg_c_7)), 0, 1)
# create data frame for fitted model
mydf <- data.frame(y = as.factor(y),
                   sex = efc$c161sex,
                   dep = to_factor(efc$e42dep),
                   npstu = efc$n4pstu,
                   education = to_factor(efc$c172code))
# fit model
fit <- glm(y ~., data = mydf, family = binomial(link = "logit"))


# plot probability curves (relationship between predictors and response)
sjp.glm(fit, vars= c('npstu', 'sex'), type = "pred",
        show.ci=T, scatter.plot = F, facet.grid=F)

```
![ci_cont](https://cloud.githubusercontent.com/assets/7460499/21239085/bf81064e-c305-11e6-81c3-e1d7b067e113.png)

What I'm looking for are "discrete" error bars wrapping around the actually observed points:
![margraph12_3](https://cloud.githubusercontent.com/assets/7460499/21239135/e8ff1254-c305-11e6-8950-d9d07bd2f04b.png)

**Comment by sjPlot** [comment]
The problem is: This plot type is generic and uses the `predict()`-function. So it also works for `glmer()` (merMod-objects). However, `lme4::predict.merMod()` does not compute CI (while `stats::predict.glm()` would do). Thus, I'm relying on the ggplot-internal CI region, instead of CI provided by the predict-function, since there's no generic CI-option for predict.

**Comment by methodds** [comment]
Hmmm.. And with the ggplot-internal CI region there are no categorical errors bars possible without changing from predicted probabilites to effects ? In a cookbook document I found [here](http://www.cookbook-r.com/Graphs/Plotting_means_and_error_bars_(ggplot2)) there are lots of this types of intervals. 

As a sidenote, I find it a little strange that using  ``facet.grid`` for effect plots changes the way CI's look because I thought this parameter is only used for overlaying graphs or returning multiple plots:

```
library(sjPlot)
library(sjmisc)

data(efc)
efc$education <- to_label(to_factor(efc$c172code))
fit <- lm(barthtot ~ c160age + c12hour + e17age+ education,
          data = efc)

sjp.lm(fit, type = "eff", vars = "education", facet.grid = F)
```
![image](https://cloud.githubusercontent.com/assets/7460499/21243971/b0aee148-c31b-11e6-8de1-d7f216ff328c.png)
I think these plots also look a little better if the bars would contain small horizontal stripes (see above), which makes the CI's easier to read.

```
sjp.lm(fit, type = "eff", vars = "education", facet.grid = T)
```
![image](https://cloud.githubusercontent.com/assets/7460499/21244039/e9582a9a-c31b-11e6-8798-0d7bb3220c91.png)

**Comment by methodds** [comment]
> The problem is: This plot type is generic and uses the predict()-function. So it also works for glmer() (merMod-objects). However, lme4::predict.merMod() does not compute CI (while stats::predict.glm() would do).

I just find the  [merTools vignette](https://cran.r-project.org/web/packages/merTools/vignettes/Using_predictInterval.html) for  predicting intervals. Maybe this is useful.

**Comment by sjPlot** [comment]
> Hmmm.. and with the ggplot-internal CI region there are no categorical errors bars possible without changing from predicted probabilites to effects ? In a cookbook document I found here there are lots of this types of intervals.

With `geom_errorbar()`, you can map data to plot errorbars, but you still need the data for the se / ci. While `geom_smooth()` automatically calculates the se/ci-bands for data. So, if I just have the predictions, but not the predicted standard errors, I can't use `geom_errorbar()`. I guess I'll look into the `predictIntervals()` from _merTools_.

> As a sidenote I find it a little strange that using facet.grid for effect plots changes the way CI's look because I thought this parameter is only used for overlaying graphs or returning multiple plots:

That is because I can use just one geom-type (geom_smooth) and then add a facet_grid to the ggplot-layers. In facet grids, you can't customize each facet-plot separately.

**Comment by sjPlot** [comment]
> I think these plots also look a little better if the bars would contain small horizontal stripes

No, not these horizontal stripes! ;-)

**Comment by methodds** [comment]
Well they are usually included for a reason because they make it a little easier for humans to infer the exact value on the y axis. But I guess its still a matter of personal preference.

**Comment by methodds** [comment]
I just tried it and it works very nice, thanks a lot for this update :) I have just one more question:  Can I also adjust manually which type of error bars is being used? As far as I understand at the moment, using ``sjp.glm`` etc. on a factor will automatically do this.

**Comment by sjPlot** [comment]
Yes, confidence Bands for continuous variables and error bars for discrete variables.

The long-term goal is to separate all data transformation parts of sjPlot into an own package, which will return the tidy data frame that can be used with ggplot. So you have, for imstande, an easy way to create the data for effects-plots and can easily build your own ggplot object.
