### ISSUE TITLE
Nitpicking: symbol for Cramer's V

### ISSUE THREAD

**Issue by methodds** [sjPlot/devel#179]
Hi,

just a very small detail: the math symbol for Cramer's V is on most text books just a large *V*, while φ is for the Phi coefficient. At the moment the Phi symbol is also displayed in ``sjt.xtab()`` and `` sjtab(fun='xtab')`` for tables larger than 2x2, where the V would be appropriate.

**Comment by sjPlot** [comment]
Cramer's V is sometimes denoted as Phi(c), that's why I used that notation.

**Comment by sjPlot** [comment]
Is this OK for you, or would you suggest changing the notation to _V_?

**Comment by methodds** [comment]
I could imagine that students will get confused and personally would prefer V, but this is really not a big thing :)

**Comment by methodds** [comment]
Thanks :)
