### ISSUE TITLE
Error in `view_spss`、`sjt.*` with multibyte var/val labels

### ISSUE THREAD

**Issue by leoluyi** [sjPlot/devel#18]
sample file:
https://drive.google.com/open?id=0B8FLxb6Zof5udUNnSTY4NXZvN2c&authuser=0

    raw.data3 <- read_spss(
      "multibyte_char_data.sav",
      enc = "UTF-8", 
      autoAttachVarLabels = T, 
      option = "foreign")

    view_spss(raw.data3, encoding = "UTF-8")

![1](https://cloud.githubusercontent.com/assets/8746961/7029024/cc8ce70a-dd8c-11e4-83f1-249b95c7cab2.PNG)

![2](https://cloud.githubusercontent.com/assets/8746961/7029028/d2409e08-dd8c-11e4-8c54-7878ba8f60e3.PNG)

    Session info ---------------------------------------------------
      setting  value                       
      version  R version 3.1.3 (2015-03-09)
      system   i386, mingw32               
      ui       RStudio (0.99.380)          
      language (EN)                        
      collate  Chinese_Taiwan.950          
      tz       Asia/Taipei

**Comment by sjPlot** [comment]
The same code works for me without any errors, and the html-page is shown properly. I guess the encoding is different for your locale, but I'm not sure how debug this issue when I can't reproduce that bug.

**Comment by eolembrain-leo** [comment]
Thanks for reply!
After changing the locale to `English_United States.1252`, it works!

    Sys.setlocale(category = "LC_ALL", "English_United States.1252")

Setting to this locale as below might reproduce the bug.

    Sys.setlocale(category = "LC_ALL", "Chinese (Traditional)_Taiwan.950")

It would be appreciated if this could be fixed for different locales.

**Comment by frankcsliu** [comment]
Hi, I have a similar locale or encoding issue. 
sjt.frq shows the labels correctly,
![pic1](https://i.imgur.com/Ir2Mo5X.png) 
but sjp.frq for the same variable won't show correct encoding of the labels. 
![pic2](https://i.imgur.com/ER9cUFV.png)

Along with the issue mentioned above by eolembrain-leo, I am looking forward to a parameter in sjp.frq for specifying encoding like in sjt.frq. Thank you.

**Comment by sjPlot** [comment]
If you build your own plot with ggplot, can you then set axis labels that are encoded and printed properly? I'm not sure whether I can address this issue in my package, or whether it's a ggplot-issue...

**Comment by frankcsliu** [comment]
Hi, Daniel,

Thanks for the quick reply!

When I build the plot using ggplot2, I cannot set axis labels but only
change axis titles.

|ggplot(data=id15, aes(x=factor(V3))) + geom_bar(width=.6) +  xlab("test")
|

As shown here,
pic1

The figure does not show the labels but variable values. I wish it has a
parameter for me to read in variable labels and variable values through
get_var_labels() and get_val_labels().

So I don’t know how well the labels are encoded and printed.

Thank you.

Frank

On 5/21/15 10:11 PM, Daniel Lüdecke wrote:

> If you build your own plot with ggplot, can you then set axis labels
> that are encoded and printed properly? I'm not sure whether I can
> address this issue in my package, or whether it's a ggplot-issue...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sjPlot/devel/issues/18#issuecomment-104289615>.
>
​

**Comment by eolembrain-leo** [comment]
@frankcsliu 
Here are some suggestions:

I always save `.sav` files with "UTF-8" encoding (you can find the settings in SPSS),
so that encoding issues would be much more less when using R packages.

![default](https://cloud.githubusercontent.com/assets/8746961/7791246/8532d866-02cf-11e5-92b2-d0a214d16c2d.PNG)

Although the input  `.sav` labels are "UTF-8",
`sjt.frq` returns your current locale encoding text, which might be "Big5", instead of "UTF-8".
So you can try different encoding settings in `sjt.frq` until you get the result you want.

```
id15 <- read_spss("../data/Total.sav", option="foreign", enc = "UTF-8")  
str(id15) 
library(sjPlot)
sjt.frq(id15$V3, encoding = "Big5")
sjp.frq(id15$V3)
```

**Comment by frankcsliu** [comment]
Thanks for the suggestions. I have spss and think your advice will work.
But I do home I won't need to go back to it just for making file
encoding correct.

I do hope it is possible to do

|sjp.frq(id15$V3, encoding = "Big5")
|

**Comment by sjPlot** [comment]
@frankcsliu you can set axis labels via the `scale` command, e.g. `scale_x_discrete(values = c("label1", "label2", "label3", "label4")`.

you can than also use the `get_val_labels()` function from `sjmisc`.

**Comment by eolembrain-leo** [comment]
(`sjPlot` version 1.8.1-3)

[data](https://drive.google.com/open?id=0B8FLxb6Zof5uN1NDU1p2LUxxT0k&authuser=0)


Label encoding error in `sjt.*` series function with `sjmisc::read_spss(method = "haven")`

```{r}
raw.data <- sjmisc::read_spss("data.sav")
```

```{r}
Encoding(get_val_labels(raw.data$Q9R))
# [1] "UTF-8" "UTF-8" "UTF-8" "UTF-8"
```

```{r}
sjt.frq(raw.data$Q9R)
# Error in gsub("class=", "style=", knitr, fixed = TRUE) : 
#   invalid multibyte string at '<a8><81><20>Marvel</caption>
#    <tr>
#      <th class="thead firsttablerow firsttablecol">value</th>
#      <th class="thead firsttablerow">N</th>
#      <th class="thead firsttablerow">raw %</th>
#      <th class="thead firsttablerow">valid %</th>
#      <th class="thead firsttablerow">cumulative %</th>
#    </tr>
```

```{r}
sjt.frq(raw.data$Q9R, encoding = "UTF-8")
# Error in gsub("class=", "style=", knitr, fixed = TRUE) : 
#   invalid multibyte string at '<a8><81><20>Marvel</caption>
# <tr>
# <th class="thead firsttablerow firsttablecol">value</th>
# <th class="thead firsttablerow">N</th>
# <th class="thead firsttablerow">raw %</th>
# <th class="thead firsttablerow">valid %</th>
# <th class="thead firsttablerow">cumulative %</th>
# </tr>
```

I'm not sure if it's also locale problem
```{r}
Sys.setlocale(locale = "Chinese_Taiwan.950")
```

**Comment by sjPlot** [comment]
@leoluyi I fixed a possible bug [in this commit](https://github.com/sjPlot/devel/commit/7fe80c82154537e58eb35bc40d17a69727fac59e), so please could you try the current GitHub-build of sjPlot and see if `view_df` still throws an error?

**Comment by sjPlot** [comment]
@frankcsliu could you please 1) re-open your issue (because I think it's not directly related to the initial issue) and 2) provide some sample data?

**Comment by leoluyi** [comment]
@sjPlot Really appreciate the great work fixing this issue! Both `view_df` and `sjt.frq` works well in my session environment.
