### ISSUE TITLE
Yates' continuity correction for sjt.xtab

### ISSUE THREAD

**Issue by sjPlot** [sjPlot/devel#181]
It seems that with the sjt.xtab() function, the chi square info at the bottom of the table always  displays values using Yates' continuity correction. Is there a way to specify that I don't want to use this correction?

**Comment by methodds** [comment]
It is using ``chisq.test`` which has a boolean parameter ``correct`` described as 

> a logical indicating whether to apply continuity correction when computing the test statistic for 2 by 2 tables: one half is subtracted from all |O - E| differences; however, the correction will not be bigger than the differences themselves. No correction is done if simulate.p.value = TRUE."

**Comment by sjPlot** [comment]
Sorry, that was just copy/paste from an email I got - I know about the `correct`-argument, it's just that I don't forget this issue. ;-)
