### ISSUE TITLE
Suggestion: Improvements to prediction plots

### ISSUE THREAD

**Issue by methodds** [sjPlot/devel#184]
Hi, 

at the moment prediction plots work just fine with up to three covariates like so:

```
data(efc)
# create binary response
y <- ifelse(efc$neg_c_7 < median(na.omit(efc$neg_c_7)), 0, 1)
# create data frame for fitted model
mydf <- data.frame(y = as.factor(y),
                   sex = to_factor(efc$c161sex),
                   dep = to_factor(efc$e42dep),
                   barthel = efc$barthtot,
                   education = to_factor(efc$c172code))
# fit model
fit <- glm(y ~., data = mydf, family = binomial(link = "logit"))


sjp.glm(fit, type = "pred", vars = c("barthel", "education", "sex"), show.ci=T)
```
![image](https://cloud.githubusercontent.com/assets/7460499/21309331/36236532-c5de-11e6-90d4-703c1666c89e.png)

It would be pretty awesome to have an option which could restrict the plots for defined covariate levels. For example, let's assume that we are only interested in the difference between lower and higher education and only for men. We maybe could rewrite the function from above like this:

``
sjp.glm(fit, type = "pred", vars = c("barthel", "education [1,3]", "sex" [1]), show.ci=T)
``
or  include an additional parameter::

``
sjp.glm(fit, type = "pred", vars = c("barthel", "education", "sex"), restrict.to=c('education = c(1,3),
sex=1))
``
The resulting plot would then only return the lines/ CI's for the given covariate levels. Do you think this is possible?

**Comment by sjPlot** [comment]
That would simply be a filter-operation, or do you have something more sophisticated in your mind?

**Comment by methodds** [comment]
no nothing sophisticated, it would really just be a handy way to only show graphs for specific covariate levels.

**Comment by sjPlot** [comment]
Ok, this one will go into [ggpredict](https://github.com/sjPlot/ggtidyr/blob/master/R/ggpredict.R), which will be the new package imported by sjPlot to create plots. pkg **ggtidyr** is intended to provide generic functions that create tidy outputs as data frames from any model input, where the returned data frame is ready to use for ggplot. 

I can't commit now, but will do tonight, and once the package **ggtidyr** comprises the basic functions (like `ggeffects()`. `ggint()` (or gginteraction), and so on), I'll submit to CRAN and implement it in sjPlot - so, I consider this issue as closed.

As a small spoiler for what will work with `ggpredict()`:

```
data(efc)
fit <- lm(barthtot ~ c12hour + neg_c_7 + c161sex + c172code, data = efc)

ggpredict(fit, vars = "c12hour")
ggpredict(fit, vars = c("c12hour", "c172code"))
ggpredict(fit, vars = c("c12hour", "c172code", "c161sex"), use.varname = TRUE)

mydf <- ggpredict(fit, vars = c("c12hour", "c161sex", "c172code"))
library(ggplot2)
ggplot(mydf, aes(x = x, y = predicted, colour = group)) +
  stat_smooth(method = "lm", se = FALSE) +
  facet_wrap(~facet, ncol = 2)

# select specific levels for grouping terms
mydf <- ggpredict(fit, vars = c("c12hour", "c172code [1,3]", "c161sex [1]"))
ggplot(mydf, aes(x = x, y = predicted, colour = group)) +
  stat_smooth(method = "lm", se = FALSE) +
  facet_wrap(~facet) +
  labs(
    y = get_y_title(mydf),
    x = get_x_title(mydf),
    colour = get_legend_title(mydf)
  )

# level indication also works for factors with non-numeric levels
# and in combination with numeric levels for other variables
library(sjmisc)
data(efc)
efc$c172code <- to_label(efc$c172code)
fit <- lm(barthtot ~ c12hour + neg_c_7 + c161sex + c172code, data = efc)
ggpredict(fit, vars = c("c12hour",
  "c172code [low level of education, high level of education]",
  "c161sex [1]"))
```

Example output from the last command:

```
# A tibble: 87 × 7
       x predicted conf.low conf.high                   group    facet response
   <dbl>     <dbl>    <dbl>     <dbl>                  <fctr>   <fctr>    <dbl>
1     70  56.99912 52.27271  61.72554  low level of education [1] Male       35
2     24  52.67787 47.02540  58.33035  low level of education [1] Male       70
3    168  28.83716 22.26802  35.40630 high level of education [1] Male       55
4    150  42.52062 35.97763  49.06361 high level of education [1] Male       20
5     50  45.02935 39.40776  50.65093 high level of education [1] Male       80
6     89  43.06244 38.03202  48.09286  low level of education [1] Male       30
7     12  77.46544 72.62470  82.30617 high level of education [1] Male       55
8     24  54.95923 49.54170  60.37677  low level of education [1] Male       55
9    125  29.38368 23.72903  35.03834  low level of education [1] Male       45
10    14  70.11491 65.39235  74.83747 high level of education [1] Male       65
# ... with 77 more rows
```

**Comment by methodds** [comment]
ah cool. thanks for the implementation and the example. So in the future sjPlot will call ggtidyr functions automatically in the background?

**Comment by sjPlot** [comment]
Yes, and I think the re-implementation of the transformation code pieces, outsourced into the ggtidyr package, will help to make the code base cleaner and more generic and extandable.

**Comment by sjPlot** [comment]
ok, I think https://github.com/sjPlot/ggtidyr/blob/master/R/ggpredict.R in its current state can be considered as "blueprint" for all following functions. The core of extending the functions is here: https://github.com/sjPlot/ggtidyr/blob/master/R/ggpredict.R#L118

You can add a simple line to the code (of course this needs to refer to a function like those starting here: https://github.com/sjPlot/ggtidyr/blob/master/R/ggpredict.R#L234) to add support for other model-types.

The functions to compute marginal effects, interactions, fixed effects etc. all should be structured like this (for fixed effects, it will most likely be some kind of wrapper for the **broom**-package-functions).
