### ISSUE TITLE
row and column manipulation in sjt.xtabs

### ISSUE THREAD

**Issue by Dev1412** [sjPlot/devel#188]
Hi,

I am using sjt.xtabs to generate some crosstabs. The output generated is well formatted compared to other packages. I now wanted to do some row and column manipulation on the **output** of the crosstab generated by sjt.xtabs. So for example my crosstab **output** has year in the column, and say two years, year 1 and year 2. I want to add a third column of growth by doing some calculation on the two columns of the **output.** So this third column will subtract year 1 from year 2 and create the third column "growth" which gives me how the 2nd year has grown / declined on certain parameters. Do we have such option?

**Comment by sjPlot** [comment]
No, since this is a very specific calculation, which can't be captured in a generic way. You probably can compute the values in the third column by hand, save them as data frame and then use `sjt.df()` to print a data frame as HTML-table.
