### ISSUE TITLE
cannot find function "read_spss" in the latest development snapshot

### ISSUE THREAD

**Issue by JiesiGuo** [sjPlot/devel#19]
I installed the  latest development snapshot.
`library(devtools)`
`devtools::install_github("sjPlot/devel")`

And then trying to load a dataset by `read_spss`. I got this error:
_Error: could not find function "read_spss"_

But `?read_spss` works well. 

If I reinstall the package using `install.packages("sjPlot")`. Everything looks fine.

**Comment by sjPlot** [comment]
See [read.me](https://github.com/sjPlot/devel), these functions have been moved into the [sjmisc-package](https://github.com/sjPlot/sjmisc) (also [on CRAN](http://cran.r-project.org/web/packages/sjmisc/index.html)).
