### ISSUE TITLE
sjt.xtab

### ISSUE THREAD

**Issue by ogsj** [sjPlot/devel#192]
Hi, is there a way to set sjt.xtab (with show.col.pct) final output to round to no decimals?

**Comment by sjPlot** [comment]
You can use the `digits`-argument.

**Comment by ogsj** [comment]
Digits=0 gives me error in total percentages?

**Comment by sjPlot** [comment]
Do you have a reproducible example? For me everything works fine.

```
library(sjstats)
library(sjPlot)
data(efc)
sjt.xtab(efc$e42dep, efc$c172code, show.col.prc = T, show.row.prc = T, show.cell.prc = T, digits = 0)
```

**Comment by ogsj** [comment]
Hi, I do, I have a csv dataset which I could mail you, where I get wrong percentages for total column, as if the rounding with digits=0 occurs somewhere too early in the calculations? Can I get the csv over to you somehow?


24 januari 2017 09:49:35 +01:00, skrev Daniel Lüdecke <notifications@github.com>:

**Comment by sjPlot** [comment]
You can send it by email. Contact data is here: https://github.com/sjPlot

**Comment by sjPlot** [comment]
It's a rounding error. The function is more precise now, but still may not be 100% accurate.
