### ISSUE TITLE
change axis labels in sjp.glmer, type = "eff"

### ISSUE THREAD

**Issue by ibleaman** [sjPlot/devel#195]
I am using `sjPlot` and the function `sjp.glmer(mymodel, type="eff"...)` to plot the marginal effects of predictors from a logistic mixed-effects model. The plot looks great, but I want to change the label of the y-axis and the labels of each of the facets. I am at a loss of how to do this. I have read the help pages and attempted to use the arguments `axis.labels`, `axis.title`, etc., but nothing helps.

Any advice? Thanks!

**Comment by sjPlot** [comment]
Labelling facets is difficult, you need a labeller-function for this (currently not supported in sjPlot). However, factor levels are automatically used as labels, so you could set the levels of the factor before fitting your model.

Regarding the y-axis: do you have a small reproducible example?

**Comment by ibleaman** [comment]
Thanks for the quick reply!
With regard to the y-axis, my question could be boiled down to:
How does one change the default text from "Predicted probabilities for RESPONSE_VARIABLE" to something different?

**Comment by ibleaman** [comment]
I figured out a way to relabel the facets. It's probably overly hacky (I am not an R expert...) but does the trick for me. I assigned my `sjp.glmer(...)` plot to a variable called `plot_marginal_effects` and then took a look at `plot_marginal_effects$plot$data$var.label` to locate the labels I wanted to overwrite. I then manually overwrote the particular bad labels.

**Comment by ibleaman** [comment]
And to change the y-axis text: `plot_marginal_effects$plot$labels$y <- "new text"`

**Comment by sjPlot** [comment]
```
library(lme4)
library(sjmisc)
data(efc)
efc$hi_qol <- dicho(efc$quol_5)
efc$grp = as.factor(efc$e15relat)
levels(x = efc$grp) <- get_labels(efc$e15relat)
mydf <- data.frame(hi_qol = to_factor(efc$hi_qol),
                   sex = to_factor(efc$c161sex),
                   education = to_factor(efc$c172code),
                   c12hour = efc$c12hour,
                   neg_c_7 = efc$neg_c_7,
                   grp = efc$grp)
fit <- glmer(hi_qol ~ sex + c12hour + neg_c_7 + (1|grp),
             data = mydf, family = binomial("logit"))
sjp.glmer(fit, type = "eff", facet.grid = F, title = c("title a", "title b", "title c"), axis.title = c("a", "b", "c"))
```
