### ISSUE TITLE
sjp.lmer, type = "fe" drops one level

### ISSUE THREAD

**Issue by maximgalchenko** [sjPlot/devel#197]
Hi,

Package: sjPlot
Version: 2.3.0
Date: 2017-02-07

I have 4 fixed effects model (TLD, SED, VL, SH) and try to plot:
sjp.lmer(models_lmer$model1, type = "fe").
Result:  I have three effects on plots, labels from first three (TLD, SED, VL), values from last (SED, VL, SH).
When I use:
sjp.lmer(models_lmer$model1, type = "fe", axis.labels =c("TLD", "SED", "VL", "SH") )
I see right result, but without TLD.

**Comment by sjPlot** [comment]
Do you have a reproducible example? You can send data by email, if you like: d.luedecke@uke.de

**Comment by maximgalchenko** [comment]
Yep, send to e-mail. Probably problem with objects of lmer function from lmerTest library.

**Comment by sjPlot** [comment]
Ok, thanks! I'll take a look at it.

**Comment by sjPlot** [comment]
When fitting the model with `lmertest`, I can't even generate the plot, because computation of the p-value results in an error (when calling `pbkrtest::get_Lb_ddf()`). Using `lme4::lmer()` directly works fine - so, the error is most likely somewhere in package _lmerTest_ or _pbkrtest_.
