### ISSUE TITLE
Question about geom.colors

### ISSUE THREAD

**Issue by methodds** [sjPlot/devel#199]
Hi,

I'm currently playing around with themes and colors a little bit. The example below raises a warning:

```

library(sjmisc)
library(sjPlot)
data(ftc)
y <- ifelse(efc$neg_c_7 < median(na.omit(efc$neg_c_7)), 0, 1)
# create data frame for fitting model
df <- data.frame(
  y = to_factor(y),
  sex = to_factor(efc$c161sex),
  dep = to_factor(efc$e42dep),
  barthel = efc$barthtot,
  education = to_factor(efc$c172code)
)
# set variable label for response
set_label(df$y) <- "High Negative Impact"
# fit model
fit <- glm(y ~., data = df, family = binomial(link = "logit"))
# print predicted propbabilities
sjp.setTheme(base = ggpubr::theme_pubr())
sjp.glm(fit, type = "pred", vars = c("barthel", "sex"),
        geom.colors= c("#00AFBB", "#E7B800"))
Warning message:
Insufficient length of color palette provided. 2 color values needed. 
```
What happens is basically that my vector of  colors is ignored and instead the basic color theme (Set1 I think) is used, as the plot would only need 2 of the 3 colors. Is there a way around this? I think it would be pretty convenient if one could provide a color palette with an arbitrary number of colors and then sjPlots only use as much colors as they would need. Ideally, one could even pass these default colors to sjp.setTheme(). What I also tried without success was passing a custom function
```
scale_colour_Publication <- function(...){
  library(scales)
  discrete_scale("colour","Publication",
           manual_pal(values = c("#386cb0","#fdb462","#7fc97f","#ef3b2c",
"#662506","#a6cee3","#fb9a99","#984ea3","#ffff33")), ... 
}
```

**Comment by methodds** [comment]
Sry another thing which is only slightly related, but  it somehow possible to pass additional theme arguments to sjp.setTheme, e.g. for the grid?

```
sjp.setTheme(base = ggpubr::theme_classic2(),
             panel.grid.major = element_line(colour = "grey40"))
```

**Comment by sjPlot** [comment]
I don't get this warning - which version of sjPlot are you using?

**Comment by sjPlot** [comment]
> Ideally, one could even pass these default colors to sjp.setTheme(). 

I'm not quite sure how this works. You can set theme options that apply globally to all plots. Colors, however, are set via `scale_*()`, which is a layer added to a plot. So, colors are set when the plot is created, and not set as theme option. I know this is possible, else all the theme-packages would not work, however, I haven't looked after this issue yet.

**Comment by sjPlot** [comment]
> Sry another thing which is only slightly related, but it somehow possible to pass additional theme arguments to sjp.setTheme, e.g. for the grid?

No, not yet. `sjp.setTheme()` was more or less an attempt to implement a theming-options with convenient defaults, and to include own theme-presets. Actually, if you want to change details in themes, `sjp.setTheme()` is not much easier or faster than directly using `ggplot2::theme()`. That's why I did not spend much time on this function...

Maybe I should spend some more time revising this function. ;-)

**Comment by methodds** [comment]
> I don't get this warning - which version of sjPlot are you using?

Sorry, I copy pasted the wrong example. This warning will be raised if you pass a vector with more colors than needed:
```
sjp.glm(fit, type = "pred", vars = c("barthel", "sex"),
        geom.colors= c("#00AFBB", "#E7B800", "#984ea3","#ffff33"))

Warning message:
Insufficient length of color palette provided. 2 color values needed. 
```
This is also stated in the documentation "*Else, if group.estimates is specified, geom.colors must be a vector of same length as groups.*", but I think this function behavior is a little unfortunate, as usually users would have one color palette that they would like to user for several cases without the need to manually trim the corresponding vector everytime.

**Comment by sjPlot** [comment]
Ok, your main issue here is fixed. Can't commit because I'm travelling, will do this when I'm back in Hamburg. Please open new issues for the other aspects you mentioned, to avoid confusion for me. ;-)
