### ISSUE TITLE
Bug in sjp.frq for leading zeros

### ISSUE THREAD

**Issue by sthesing** [sjPlot/devel#2]
If the count of the first bar of a frequency plot is 0, wrong values are assigned to the plots. 
Two reproducible examples with different results, depending on how the level order is assigned.

    mydf <- data.frame(Q=c(rep("No", 5), rep("Maybe", 3)))
    levels(mydf[,1]) <- c("Yes", "No", "Maybe")
    sjp.frq(mydf[,1], axisLimits.y=c(0,7))

![bugreport](https://cloud.githubusercontent.com/assets/464966/5392640/ee6c0592-8128-11e4-9ac3-4eac4566b42f.png)

    mydf <- data.frame(Q=c(rep("No", 5), rep("Maybe", 3)))
    mydf[,1] <- ordered(mydf[,1], levels=c("Yes", "No", "Maybe"))
    sjp.frq(mydf[,1], axisLimits.y=c(0,7))

![bugreport2](https://cloud.githubusercontent.com/assets/464966/5392751/347f827e-812a-11e4-8af9-ae803a82fa80.png)

**Comment by sjPlot** [comment]
I haven't solved this issue yet, however, using `to_value` in the latest [sjmisc](https://github.com/sjPlot/sjmisc/)-snapshot, solves the problem (see https://github.com/sjPlot/sjmisc/commit/520e2a829a2a736fb0fe1650721e4b176a87f52f).

`sjp.frq(to_value(mydf[,1]), axisLimits.y=c(0,7))` works for me.
so, issue "half-closed" ;-)

**Comment by sjPlot** [comment]
Ok, found the bug. I will commit the latest version this evening.

**Comment by sthesing** [comment]
Thanks! Works fine.

**Comment by sthesing** [comment]
Hi Daniel, 
seems this issue is back. I'm on version sjPlot_1.8.3-3. The examples of my original post yield the exact same results as they did back then.
