### ISSUE TITLE
boolean predictors not supported in sjp.int for mixed models

### ISSUE THREAD

**Issue by rubenarslan** [sjPlot/devel#20]
recoding a factor into 0/1 does it for me.

**Comment by sjPlot** [comment]
Do you have a reproducible example?

Following works for me, where `mydf$sex` is a factor with levels 1 and 2:

    library(sjmisc)
    data(efc)
    # create data frame with variables that should be included
    # in the model
    mydf <- data.frame(usage = efc$tot_sc_e,
                       sex = efc$c161sex,
                       education = efc$c172code,
                       burden = efc$neg_c_7,
                       dependency = efc$e42dep)
    # convert gender predictor to factor
    mydf$sex <- relevel(factor(mydf$sex), ref = "2")
    # fit "dummy" model
    fit <- lm(usage ~ .*., data = mydf)
    
    library(sjPlot)
    

as well as

    levels(mydf$sex) <- c("A", "B")
    # re-fit model
    fit <- lm(usage ~ .*., data = mydf)
    sjp.int(fit, plevel = 1)

**Comment by rubenarslan** [comment]
Sure! Sorry, I thought it was about factors everywhere, but it's booleans in combination with lme4 (have only tested lm otherwise).
The error message:
>Error in `[.data.frame`(fitdat, interactionterms[[1]][1]) : 
  undefined columns selected

```
library(sjmisc)
data(efc)
# create data frame with variables that should be included
# in the model
mydf <- data.frame(usage = efc$tot_sc_e,
									 sex = efc$c161sex,
									 education = efc$c172code,
									 burden = efc$neg_c_7,
									 dependency = efc$e42dep,
									 randomeff = rep(1:10,length.out = nrow(efc)))
# convert gender predictor to factor
mydf$sexf <- relevel(factor(mydf$sex), ref = "2")
mydf$sexb <- mydf$sex == 2
# fit "dummy" model
library(lme4);library(sjPlot)
fit <- lme4::lmer(usage ~ sex*burden + (1|randomeff), data = mydf)
sjp.int(fit)
fit <- lme4::lmer(usage ~ sexf*burden + (1|randomeff), data = mydf)
sjp.int(fit)
# this one breaks
fit <- lme4::lmer(usage ~ sexb * burden + (1|randomeff), data = mydf)
sjp.int(fit)
fit <- lm(usage ~ sexb * burden * education, data = mydf)
sjp.int(fit)
```

**Comment by sjPlot** [comment]
I fixed that (for `type = "cond"`), however, for `type = "eff"` I can't do much, because the `effects` package cannot cope with booleans. I'll commit to Git this evening.
