### ISSUE TITLE
Suggestion: Wrappers for ggpubr plots

### ISSUE THREAD

**Issue by methodds** [sjPlot/devel#202]
Hi,

this is only a low priority suggestion, but [ggpubr](http://www.sthda.com/english/rpkgs/ggpubr/) has a very nice design for density plots, boxplots and violin plots. It would be nice if sjPlot would provide (labeled) wrappers for these functions.

![image](https://cloud.githubusercontent.com/assets/7460499/22877772/3dc13e84-f1d7-11e6-8dfa-207477de432c.png)

**Comment by sjPlot** [comment]
What do you mean by "labelled wrapper"?

**Comment by methodds** [comment]
Well just the usual sjPlot convenience, such that labels will be integrated in plots automatically :)

**Comment by sjPlot** [comment]
Ah, I understand. The problem is, that this package does not provide geoms, but completely builds the plot. I would say that this is an issue for the maintainer of ggpubr, and maybe (s)he could rely on sjmisc to add support for labelled data.

**Comment by methodds** [comment]
Okay, I might just contact the maintainer and ask whether this would be of interest. I guess this issue can be closed then.

**Comment by sjPlot** [comment]
At least for violin plots, you get similar results:

```
library(ggpubr)
library(sjPlot)
library(ggplot2)
theme_set(theme_pubr())
sjp.grpfrq(ToothGrowth$len, ToothGrowth$dose, type = "violin", geom.colors = c("#00AFBB", "#E7B800", "#FC4E07"), ylim = c(-5, 45))
```

![rplot](https://cloud.githubusercontent.com/assets/4901179/22967592/6233ff86-f367-11e6-8c47-14ebe51a4cb6.png)
