### ISSUE TITLE
axisLimits.y is not working in sjp.lmer with type "fe" 

### ISSUE THREAD

**Issue by hhibshi** [sjPlot/devel#204]
Please provide a fix as I would like to be able to adjust the y axis to a specific range for consistency among all my figure. It works for type ="fe.std" but I need the fixed effects!

Thanks!

**Comment by sjPlot** [comment]
Do you have a reproducible example? `axisLimits.y` is a deprecated argument, so you're probably using an older version of sjPlot, and this issue might already been fixed.

**Comment by hhibshi** [comment]
I am using version 1.9.2. I can send you pictures of the example.

**Comment by hhibshi** [comment]
I updated all packages in R before working

**Comment by sjPlot** [comment]
Ok, latest package version is 2.3.0, and I think this issue is already fixed.

**Comment by hhibshi** [comment]
is it in the cran repository? 

I tried installing it from the tar file but I got the message: 
 installation of package had non-zero exit status

**Comment by hhibshi** [comment]
never mind. I think I found the new version in CRAN. 

Thanks!

**Comment by sjPlot** [comment]
I'll close this issue here. Please re-open if you still face any problems with the current sjPlot-version.
