### ISSUE TITLE
Suggestion: glmmTMB compatibility

### ISSUE THREAD

**Issue by MichaelRatajczak** [sjPlot/devel#205]
Hi, 

There is a new package, currently in beta, used for generalised linear mixed effects modelling -- glmmTMB (https://github.com/glmmTMB/glmmTMB). I was wondering if you could make sjPlot compatible with it?

Kind regards,
Michael

**Comment by sjPlot** [comment]
Once the package is on CRAN, and depending on the generic functions it supports, integration might be easy. Nice to see zero-inflated models comin to glmm.

**Comment by sjPlot** [comment]
OK, issue can be closed, I'm addressing it over here:
https://github.com/sjPlot/ggtidyr/commit/38cc418ec801d12b865e7cb78ad136806c1c5a58

Predictions already included, more will follow. However it will take some time until the pkg `ggtidyr` is finished.
