### ISSUE TITLE
Cannot plot all categorical fixed effects

### ISSUE THREAD

**Issue by jebyrnes** [sjPlot/devel#207]
Working on a project where I want to use sjPlot to get all of the means of categorical fixed effects, but, even it I use `-1` to get the means rather than treatment contrast, `sjp.lmer` will not plot all of the levels.

```
#where's the intercept?
data(Oats)
oat_mer <- lmer(yield ~ Variety + (1|Block), data=Oats)
sjp.lmer(oat_mer, type="fe")

#only shows 2 varieties
oat_mer_noint <- lmer(yield ~ Variety + (1|Block) - 1, data=Oats)
sjp.lmer(oat_mer_noint, type="fe")
```

**Comment by sjPlot** [comment]
Where do I find the dataset _Oats_? I need a reproducible example.

**Comment by jebyrnes** [comment]
Oops - it’s in nlme.

On Feb 16, 2017, at 1:40 PM, Daniel Lüdecke <notifications@github.com<mailto:notifications@github.com>> wrote:


Where do I find the dataset Oats? I need a reproducible example.

**Comment by sjPlot** [comment]
Ok, I now understand the problem. Simply add `show.intercept = TRUE` to the function call:

`sjp.lmer(oat_mer, type = "fe", show.intercept = T)`

For the second example, this will not change the intercept-label on the y-axis, so you have to use `string.interc`.

`sjp.lmer(oat_mer_noint, type = "fe", show.intercept = T, string.interc = "VarietyGolden Rain")`

**Comment by jebyrnes** [comment]
Hrm. OK. Any chance for no fixed intercept models, this behavior can be changed? Would ease a lot of plotting problems.

**Comment by sjPlot** [comment]
Do you mean changing the default value for argument `show.intercept`?

**Comment by jebyrnes** [comment]
Sure - or at least when -1 is in the model.

On Feb 16, 2017, at 3:46 PM, Daniel Lüdecke <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you mean changing the default value for argument show.intercept?
