### ISSUE TITLE
Can't change line colors in sjp.glmer

### ISSUE THREAD

**Issue by CJustice77** [sjPlot/devel#208]
I've attempted to change the line colors grey scale or just black using sjp.glmer. The argument "geom.colors" does not appear to work for this type of plot. Here's some example code:

# fit model
library(lme4)
# create binary response
sleepstudy$Reaction.dicho <- 
  dicho(sleepstudy$Reaction, dich.by = "median")
# fit model
fit <- glmer(Reaction.dicho ~ Days + (Days | Subject),
             sleepstudy, family = binomial("logit"))
sjp.glmer(fit, type="ri.slope", ri.nr=1, show.ci=F, facet.grid=F,geom.colors="Greys")

Note that geom.colors="Greys" has no effect. This code produces the default color palette regardless of what you put in for geom.colors.

**Comment by sjPlot** [comment]
`geom.colors` was irgnored by plot-type `type = ri.slope`. I added support for geom.colors now, use `geom.colors = "gs"` or `geom.colors = "bw"` for grayscale- or b/w-colors.
