### ISSUE TITLE
Warning for sjt.lm()

### ISSUE THREAD

**Issue by methodds** [sjPlot/devel#213]
Hi,

using ```sjt.lm()``` to show two nested models raises the following warning (there is a small typo in "encouter"):
```
Fitted models have different coefficients. Grouping may not work properly. 
Set `group.pred = FALSE` if you encouter cluttered labelling.
```
Is this warning important? Nesting models is very common and I think there is no need to throw a warning here. Maybe the suggestion with ```group.pred``` could instead be included in the documentation?

**Comment by sjPlot** [comment]
It's not a warning, it's a message. ;-)
It occurs when you have categorical predictors with more than 2 levels, and multiple models in the table that have different predictors. Then `sjt.lm()` has to "group" predictors in the table layout, which might not be exact.

See [this example](http://strengejacke.de/sjPlot/sjt.lmer/), paragraph _Grouping predictors_.

**Comment by methodds** [comment]
I see, thanks. But what would be the reason to rather use a message than stating this in the documentation? Messages and warnings are for example also included in rmarkdown documents right?

**Comment by sjPlot** [comment]
Messages and warnings are quite common in functions, to give user a hint when a function shows unexpected behaviour. If your only concern is markdown, rather use `message=FALSE` or `warnings=FALSE`. See https://yihui.name/knitr/options/.

**Comment by methodds** [comment]
ok
