### ISSUE TITLE
sjp.glm plots

### ISSUE THREAD

**Issue by methodds** [sjPlot/devel#214]
Hi, I'm currently working through several plots of the following example:

```
library(sjmisc)
library(sjPlot)
data(efc)

# create binary response
y <- ifelse(efc$neg_c_7 < median(na.omit(efc$neg_c_7)), 0, 1)
# create data frame for fitted model
mydf <- data.frame(y = as.factor(y),
                   sex = to_factor(efc$c161sex),
                   dep = to_factor(efc$e42dep),
                   barthel = efc$barthtot,
                   education = to_factor(efc$c172code))
# fit model
fit <- glm(y ~ sex * barthel + education + dep, data = mydf,
           family = binomial(link = "logit"))
```
Several plots return unexpected results:

```sjp.glm(fit, 'ma')```

![image](https://cloud.githubusercontent.com/assets/7460499/23367616/222a581a-fd0b-11e6-909f-df2ab566b89c.png)

I don't understand how this plot relates to model assumptions. For me it looks just like a (exponentiated) coefficient plot. 

```sjp.glm(fit, 'prob', vars=c("barthel", "sex", "education"), show.ci=T, facet.grid=F)```

![image](https://cloud.githubusercontent.com/assets/7460499/23367794/e89a7066-fd0b-11e6-8a5d-ac8285a10169.png)

I assume this is not working because of the interaction effect? If so, why? Shouldn't there be a way to correctly account for the interaction terms without having to use ```sjp.int()```? Is this just a matter of correctly parsing the model formula string?

```sjp.glm(fit, 'prob', vars=c("barthel * sex"),  show.ci=T)```

Returns this:
![image](https://cloud.githubusercontent.com/assets/7460499/23368078/e3ef8c08-fd0c-11e6-8ea8-6a3cdac56fd9.png)

```sjp.glm(fit, 'eff', show.ci=T)```
![image](https://cloud.githubusercontent.com/assets/7460499/23367902/56288a28-fd0c-11e6-99d9-c56902db360d.png)

Also excludes variables that are included in interaction term. And I don't think the y axis label "Odds Ratios" is correct. Using ```sjp.glm(fit, 'eff', vars=c("barthel * sex"), show.ci=T)```returns the same plot.

**Comment by sjPlot** [comment]
> Several plots return unexpected results:
> sjp.glm(fit, 'ma')

That's more a historical reason. In past versions of sjPlot, coefficients of the updated model w/o outliers were plotted, and compared to the original model. I guess I can remove this plot.

**Comment by sjPlot** [comment]
> I assume this is not working because of the interaction effect? If so, why?

The interaction effect would always require at least to lines, and this plot-type is only intended to plot the relationship between predictor and response on the "linear" scale.

**Comment by sjPlot** [comment]
> Also excludes variables that are included in interaction term. 

This is intentional. I wanted to distinguish between interaction effects and "simple" effects. That's why I have two functions, `sjp.int()` and `sjp.eff()`.

**Comment by methodds** [comment]
Ok, so maybe it would be a good idea to explicitly state in the documentation of ``sjp.glm`` that these plots are not intended to work with interaction effects and directly link to ``sjp.int``.

**Comment by sjPlot** [comment]
Well, the plot-types _slope_ and _prob_ should be used with caution, as these ignore covariates. Hence, the shown lines / values are not adjusted for covariates, which - however - is done for `type = "pred"` or `type = "eff"`. `type = "slope" is most likely useful to see whether there's a linear relationship between predictor and response, or if you should better use a polynomial term, for instance.

**Comment by sjPlot** [comment]
`type = "eff"` should give a message that interaction terms are ignored, however, there's a new bug that this message is never printed. Fixed now.
