### ISSUE TITLE
Question regarding installation problems

### ISSUE THREAD

**Issue by methodds** [sjPlot/devel#221]
Hi, 
I just set up a new OS (windows 10), installed the latest R version, RStudio and Rtools, and then tried to install sjPlot, sjmisc and sjstats from github. However, I regularly received  " there is no package called ..." warnings and had to manually install these packages. I had to install ~ 10 packages this way (e.g. "minqa, "nloptr", "modeltools", "reshape2", and setting "dependencies = TRUE" did not help. Do you have an idea what's going on here?

**Comment by sjPlot** [comment]
This looks like multilevel-model-stuff to me (https://cran.r-project.org/web/packages/lme4/index.html). Is this in any way related to my packages?

I personally do never install my packages from GitHib, I just click on "Build & Reload" ;-)

**Comment by methodds** [comment]
> Is this in any way related to my packages?
Well it happened only for trying to install them, the problem was not occuring for other packages. But I fixed it now and although I'm not sure maybe I just messed something. 
In two weeks I'll install the packages on a number of computers and will report back in case of any issues,  this can be closed now :)

**Comment by sjPlot** [comment]
sjPlot is ready to submit, currently, win-builder seems to have some server-troubles. Once all checks are passed, I'll submit. The two other packages will follow within the next two weeks, I guess.

**Comment by helix123** [comment]
Instead of win-builder you could also try the new builder of R-Hub: 
https://builder.r-hub.io/

**Comment by sjPlot** [comment]
OK, thanks, didn't know that one. Are the checks similar to win builder?
