### ISSUE TITLE
error in a clean install of sjPlot

### ISSUE THREAD

**Issue by carioca67** [sjPlot/devel#222]
this is what I am getting

> install.packages("sjPlot")
Installing package into ‘C:/Users/drezn/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
also installing the dependencies ‘sjmisc’, ‘sjstats’

  There is a binary version available but the source version is later:
       binary source needs_compilation
sjPlot  2.3.0  2.3.1             FALSE

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/sjmisc_2.3.0.zip'
Content type 'application/zip' length 358753 bytes (350 KB)
downloaded 350 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/sjstats_0.8.0.zip'
Content type 'application/zip' length 206047 bytes (201 KB)
downloaded 201 KB

package ‘sjmisc’ successfully unpacked and MD5 sums checked
package ‘sjstats’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\drezn\AppData\Local\Temp\Rtmp8WXZye\downloaded_packages
installing the source package ‘sjPlot’

trying URL 'https://cran.rstudio.com/src/contrib/sjPlot_2.3.1.tar.gz'
Content type 'application/x-gzip' length 1796118 bytes (1.7 MB)
downloaded 1.7 MB

* installing *source* package 'sjPlot' ...
** package 'sjPlot' successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'multcomp'
ERROR: lazy loading failed for package 'sjPlot'
* removing 'C:/Users/drezn/Documents/R/win-library/3.3/sjPlot'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-33~1.2/bin/x64/R" CMD INSTALL -l "C:\Users\drezn\Documents\R\win-library\3.3" C:\Users\drezn\AppData\Local\Temp\Rtmp8WXZye/downloaded_packages/sjPlot_2.3.1.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘sjPlot’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\drezn\AppData\Local\Temp\Rtmp8WXZye\downloaded_packages’

**Comment by sjPlot** [comment]
> Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) 
> there is no package called 'multcomp'

This might be due to temporary server problems with CRAN, which occured this weekend. Or try to install pkg _multicomp_ first, then sjPlot.

**Comment by carioca67** [comment]
thank you so much ; i did that and it resolved it
