### ISSUE TITLE
Maximum Variable Label Length on write_spss()

### ISSUE THREAD

**Issue by m-dinardo** [sjPlot/devel#25]
Hi,

When I use the write_spss function with variable.label attributes, the labels appear to export properly into the .sav, however they are cut off after 120 characters. I believe 120 characters was the limit in previous versions of SPSS, but I was wondering if there was a way to change this limit. The labels I need are somewhat lengthy survey questions, so it's important the text isn't cut off after 120 characters, and I've had trouble finding help for this issue elsewhere.

Thanks for the great package.

**Comment by sjPlot** [comment]
Hi,
the `write_spss` function now belongs to the [sjmisc](https://github.com/sjPlot/sjmisc) package, but that's just for information and not really important. However, the write_sav function is a simple wrapper for the write-function of the haven-package, so I will re-open the issue [over there](https://github.com/hadley/haven)...

**Comment by m-dinardo** [comment]
Thank you very much for the help.
