### ISSUE TITLE
(g)lmer related functions reporting lme4 not installed when it is installed

### ISSUE THREAD

**Issue by craddm** [sjPlot/devel#28]
R version 3.2, latest sjPlot (1.8) from the repository. Following your example use of sjp.glmer(), it reports that lme4 is not installed, although lme4 is both installed and functioning:

```
# fit model
library(lme4)
Loading required package: Matrix
Loading required package: Rcpp
# for "dicho" function etc.
library(sjmisc)
# create binary response
sleepstudy$Reaction.dicho <- dicho(sleepstudy$Reaction, dichBy = "md")
# fit model
fit <- glmer(Reaction.dicho ~ Days + (Days | Subject),
             sleepstudy,
             family = binomial("logit"))
sjp.glmer(fit)
Error: Package 'lme4' needed for this function to work. Please install it.
```

**Comment by sjPlot** [comment]
It's an annoying typo that has been fixed in the latest GitHub snapshot already.

It should be 'arm', not 'lme4' in this case. So, just install package arm.

**Comment by liuvic** [comment]
I get the below error:

> Error: package or namespace load failed for ‘sjPlot’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
>  there is no package called ‘effects’

**Comment by strengejacke** [comment]
> there is no package called ‘effects’

Just install that package. Or install all pkg from scratch, with dependencies:
`install.packages(c("sjlabelled", "sjmisc", "sjstats", "ggeffects", "sjPlot"), dependencies = TRUE)`
