### ISSUE TITLE
sjt.corr not showing p values for cor objects

### ISSUE THREAD

**Issue by helix123** [sjPlot/devel#30]
Seems like sjt.corr does not display p values (nor indicates significance by asteriks) when a cor object is passed. It works with a data.frame passed. I am using version 1.8 from CRAN.

````
df <- as.data.frame(cbind(rnorm(10),
                          rnorm(10),
                          rnorm(10),
                          rnorm(10),
                          rnorm(10)))

# significance is indicated
sjt.corr(df) 

cor_object <- cor(df)

# significance neither indicated nor p values printed
sjt.corr(cor_object)
sjt.corr(cor_object,
         showPValues = TRUE)

**Comment by helix123** [comment]
Uh, this might be related to the different correlation coefficents (Pearson vs. Spearman) used. cor() uses Pearson by default, sjt.corr uses Spearman.

**Comment by sjPlot** [comment]
No, this is just because the returned object by `cor` only contains the correlation values (simple matrix). There's no information where I can get the p-values from (if you know any, please let me know...)

**Comment by helix123** [comment]
True. `cor()` just returns a matrix. I suggest a tiny update to the documentation of `sjt.corr()`?
"data &nbsp; &nbsp;&nbsp;       A correlation object, built with the R-cor-function, or a data frame which correlations should be calculated."
=> I think, "correlation object" is a bit misleading here then. Could be "data&nbsp;&nbsp;&nbsp; A matrix with correlation coefficients as returned by the cor() function [...]"

`showPValues`, `pvaluesAsNumbers`, and `fadeNS` could be updated to reflect that the original data is needed for everything involving significance and that the matrix as returned by `cor()` is not sufficient for these features.

**Comment by helix123** [comment]
What about slight modifications to the documentation of `showPValues`, `pvaluesAsNumbers`, and `fadeNS`?

**Comment by sjPlot** [comment]
I've updated the docs and added a `See 'Note'` to all parameters, and in the Note-section I added a short explanation that cor-objects don't show p-values.

**Comment by helix123** [comment]
Great! Sorry, have not seen that commit.
