### ISSUE TITLE
crossed random effects break type="eff"

### ISSUE THREAD

**Issue by rubenarslan** [sjPlot/devel#33]
It seems that the effects package somehow hangs, when there are two random effects. sjPlot is indirectly affected by this, and I didn't quickly find out where to lodge bugs for `effects`.

**Comment by sjPlot** [comment]
Could you please try to compute effects directly via the `effects` package, e.g. using `allEffects(...)`? And then set the parameter `KR=FALSE`? I contacted the author of the effects-package, and this was his guess for a possible reason for this issue...

**Comment by rubenarslan** [comment]
Yes, that does it, thanks! Since this is for computing standard errors, shouldn't `showCI=F` in sjp.int also automatically entail `KR=F`?

**Comment by sjPlot** [comment]
I didn't know about that option, but I can fix this issue so the function works properly.

**Comment by sjPlot** [comment]
**effects**-package always computes standard errors. With `KR = T` (default, if package **pbkrtest** is installed), it sometimes hangs due to slow computation. However, in the next version of the **effects**-package, this parameter should default to `FALSE`.

**Comment by sjPlot** [comment]
Could you please check whether it now works with the latest development build of sjPlot?

**Comment by rubenarslan** [comment]
Still hangs when using sjp.int. I installed with `devtools::install_github(sjPlot/devel")` and used a fresh session.

**Comment by sjPlot** [comment]
hm, strange. Maybe there's another issue? Is it possible to send the data and / or fitted model (as .RData)?

**Comment by sjPlot** [comment]
Ok, seems to be a memory-issue, and not directly sjPlot nor effects package related. I'll do some tests to investigate further...

**Comment by rubenarslan** [comment]
Cool, thanks for digging so deeply! There's something odd going on, because just plotting using plot(allEffects(m2, KR = F)) doesn't take anywhere near this long.

**Comment by sjPlot** [comment]
> because just plotting using plot(allEffects(m2, KR = F)) doesn't take anywhere near this long.

Not for me. Even without plotting, just using `allEffects`, takes the same time. It's only that `sjp.int` calls `allEffects` twice, thus doubling the time to finish the calculations for the plot...

I'm not sure how to address this right now. I call `allEffects` first to find interaction terms, then a second time _if_ at least one of the interaction terms is continuous to calculate effects for specific values of the continuous interaction term.

The first call to `allEffects`, which is just to find any interaction terms, might be redundant, however, `allEffects` supports many model types/classes, and I don't know all the different structures (e.g. of `gls` or so), which I need to know to extract interaction terms.

**Comment by sjPlot** [comment]
As "breaking" crossed random effects does no longer seem to be the issue, I'll close this issue again. I'm not sure how to improve performance in this case, it seems to me an issue related to the `effects` package...

**Comment by rubenarslan** [comment]
I'm sorry, I was comparing apples and oranges.

This is fast:
```r
system.time({plot(effect("Cue*g_factor_Man", m2, KR = F), x.var="g_factor_Man",z.var="Cue",multiline=T)})
#   user  system elapsed 
#  1.914   0.020   1.947 
```

But allEffects also takes ages for me.

I think my favorite solution would be for sjp.int to have a second interface like effect, where you can specify the interaction by hand. Computing allEffects (twice) for large datasets seems wasteful. I've looked into the effects package source, unfortunately their "determine interaction from formula" stuff isn't so modularised that it would be easy to pull out. In the meantime, `se=F` could probably be specified in the allEffects call that is just there to find interactions, that should speed things up a little? And maybe the second call could ignore the covariates that aren't involved in the interaction, i.e. just call effect or Effect?

**Comment by sjPlot** [comment]
I didn't see any solution for improving performance when using `allEffects`, so I added a parameter `int.term` for `type = "eff"` to plot selected interaction terms only.

**Comment by rubenarslan** [comment]
Cool, great solution for now. Would be cool if there was a more modularised
"get this info from this model" package, I know only broom etc.
