### ISSUE TITLE
'by' argument much too small

### ISSUE THREAD

**Issue by ringprince** [sjPlot/devel#37]
When feeding my logistic regression model into sjp.glm I see this:

    > sjp.glm(model.logreg)
    Waiting for profiling to be done...
    Error in seq.default(lower_lim, upper_lim, by = gridBreaksAt) : 
      'by' argument is much too small

I tried to pass several values for gridBreaksAt from 0.01 to 100000000 to no avail.

The example from the help works fine.

**Comment by sjPlot** [comment]
Do you have data for a reproducible example, or could you send me the data/fitted model as `RData` file?

**Comment by ringprince** [comment]
Data sent off-line.

**Comment by sjPlot** [comment]
See e-mail, function works, however, the `gridBreaksAt`-argument needs to be *very* large in this case due to large odds ratio values.

**Comment by Sankalp1233** [comment]
What do you need to make the gridBreaksAt argument
