### ISSUE TITLE
return plot-object as well for sjp.(g)lm when type = "vif"

### ISSUE THREAD

**Issue by ringprince** [sjPlot/devel#38]
According to the documentation, the return value of sjp.glm is a 'structure' with the ggplot object in the plot 'element'.

This is not true when the type is set to 'vif'.  But the resulting ggplot object should be returned here as well.

**Comment by sjPlot** [comment]
I have updated the documentation. Currently, model assumption functions should not return any plot, only the updated model with removed outliers. Perhaps this may be an option for future releases.

**Comment by ringprince** [comment]
I am not sure I understand this comment.  Removed outliers?

sjp.glm produces a plot -- even if type="vif".  The plot just is not returned.  I can confirm that the documentation is consistent with the behaviour now.  But I'd much prefer to have the ggplot object returned to be able to further tweak it to my needs.

**Comment by sjPlot** [comment]
If you refer to the very last plot of model-assumptions, this is the same one as `sjp.glm(fit)`. `type = "ma"` first checks the model for outliers, and if there are any, they are being removed and an updated model w/o outliers is re-fitted. This updated `glm`-object is returned. Set `showOriginalModelOnly` to `FALSE` to see plots for both models, original and updated.

**Comment by ringprince** [comment]
This is an example what should be possible, I'd say.  And easy to achieve.  Sorry, should have posted code right in the beginning:

﻿     # prepare dichotomous dependent variable
     y <- ifelse(swiss$Fertility < median(swiss$Fertility), 0, 1)
    
     # fit model
     fitOR <- glm(y ~ swiss$Education + swiss$Examination + swiss$Infant.Mortality + swiss$Catholic,
                  family = binomial(link = "logit"))

     sjp.glm(fitOR, type="vif")$plot + theme_bw()

**Comment by sjPlot** [comment]
Sorry for confusion, I was talking about `type = "ma"`, not `type = "vif"` - my fault... Currently, you can get access to the plot only via `last_plot()` function from ggplot. I re-open this issue and may add the plot as return value as well to that function.
