### ISSUE TITLE
Package 'lme4' needed for this function to work

### ISSUE THREAD

**Issue by hassanjfry** [sjPlot/devel#41]
#my model with lmer function

model_2 = lmer (systolic_BP ~ time2 + (1 + time2 | ID),  REML = FALSE, data = subset_data)
summary (model_2)

#I recieve the following error although "lme4" is installed and running
> sjp.lmer(model_2)
Error: Package 'lme4' needed for this function to work. Please install it.

**Comment by sjPlot** [comment]
See https://github.com/sjPlot/devel/issues/28
Package-update was just submitted to CRAN, also fixing this issue.
