### ISSUE TITLE
sjp.int plot with continuous moderator

### ISSUE THREAD

**Issue by spavic** [sjPlot/devel#42]
Hi, I am trying to make an interaction plot for a logit model (binary dependent variable) where both independent and moderating variable are continuous. I use meansd to get three curves for moderation. However, I keep getting the following error message:

Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
  contrasts can be applied only to factors with 2 or more levels
In addition: Warning messages:
1: In mean.default(X[, name]) :
  argument is not numeric or logical: returning NA
2: In mean.default(X[, name]) :
  argument is not numeric or logical: returning NA

Tried to google, but still not found a proper solution. (Still rooky with R).

Any inputs? Thanks.

**Comment by sjPlot** [comment]
Which type of plot are you running? Cond, eff or emm?

**Comment by spavic** [comment]
Eff

**Comment by sjPlot** [comment]
Ok, might be an issue or bug associated with the effects Package, but i will try to figure it out .

**Comment by spavic** [comment]
Thanks a lot.

**Comment by sjPlot** [comment]
Do you convert vectors _inside_ your formula? Like `y ~ as.factor(income))`?

**Comment by spavic** [comment]
I have a factor(year) for year dummies... Can that be an issue? I will check now...

**Comment by sjPlot** [comment]
Yes, you should convert to factor outside the formula.

    year <- as.factor(year)
    lm(y ~ year)

**Comment by spavic** [comment]
Great. Works beautify. Thank you very much.

**Comment by spavic** [comment]
P.S. Why is there no axisLimits.x, for selecting a range of values on x-axis?

**Comment by sjPlot** [comment]
I wonder whether it makes sense to omit valid values from a predictor? No matter whether I have a factor (lo/mid/high) or a continuous variable (0 to 50) along the x-axis, why should I just look at a specific interval or value?

I haven't thought deeper about this issue, but for me it was just clear to use the complete range of the variable. However, I'm open to to add a parameter like `axisLimits.x` to the function, if there are good reasons for it.

**Comment by spavic** [comment]
My question was going more towards the visualization rather than the statistical logic behind it. For example, one might be particularly interested in certain range of values of a predictor (e.g., between the quantiles or around the area where moderation lines cross each other in the meansd setting of moderators). Does this make any sense to you?

**Comment by sjPlot** [comment]
So you're asking for a kind of "zoom"-functionality? I can't imagine any use case right now, which doesn't mean that it does make sense indeed. However, none of the sjPlot-functions has an `axisLimits.x`-parameter, so if this feature is useful for `sjp.int`, it might apply to other functions as well... I have to check that.
Could you please open another issue for this, so your request won't get lost?

**Comment by spavic** [comment]
I work in the field of organizational theory and it is very common to see in top-tier journals that authors limit both main predictor and moderator to a meansd setting. Unfortunatelly, in our field STATA is still a dominant software and most of the commonly used tools are therefore developed for STATA; only recently more specialized R packages started to appear. You package does great with some of the things we could not easily (without advanced knowledge) do in R so far.
