### ISSUE TITLE
sjt.frq outputs items in wrong order

### ISSUE THREAD

**Issue by jemus42** [sjPlot/devel#46]
Example:

    testdata <- structure(c(7L, 8L, 8L, 7L, 7L, 7L, 8L, 7L, 7L, 7L, 7L, 8L, 7L, 
                            7L, 7L, 7L, 7L, 9L, 7L, 8L, 8L, 8L, 7L, 7L, 7L, 7L, 7L, 8L, NA, 
                            8L, 8L, 4L, 8L, 7L, 8L, 7L, 8L, 7L, 8L, 7L, 7L, 7L, 7L, 8L, 6L, 
                            8L, 7L, 7L, 8L, 7L, 7L, 7L, 8L, 8L, 7L, NA, 7L, 7L, 7L, 7L, 7L, 
                            7L, 7L, 7L, 8L, 7L, 7L, 7L, 8L, 7L, 8L, 7L, 6L, 7L, 7L, 7L, 8L, 
                            8L, 7L, 8L, 8L, 4L, 8L, 7L, 8L, 8L, 8L, 8L, 7L, 7L, 7L, 8L, 8L, 
                            8L, 9L, 8L, 8L, 8L, 7L, 7L, 4L, 8L, 8L, 4L, 5L, 7L, 8L, 4L, 6L, 
                            7L, 6L, 4L, 4L, 6L, 4L, 7L, 7L, 7L, 8L, 8L, 4L, 4L, 4L, 4L, 4L, 
                            4L, 8L, 4L, 4L, 7L, 7L, 7L, 4L, 7L, 7L, NA, 4L, 8L, 4L, 4L, 8L, 
                            4L, 8L, 4L, 8L, 7L, 7L, 8L, 6L, 8L, 4L, 8L, 8L, 7L, 8L, 7L, 8L, 
                            8L, 8L, 8L, 4L, 8L, 6L, 6L, 4L, 7L, 8L, 7L, 8L, 7L, 7L, 4L, 8L, 
                            3L, 6L, 6L, 8L, 7L, 7L, 4L, 3L, 6L, 4L, 6L, 4L, 7L, NA, 8L, 4L, 
                            4L, 8L, 6L, 8L, 8L, 7L, 8L), .Label = c("Noch Schüler", "Schule beendet ohne Abschluss", 
                                                                    "Hauptschulabschluss/Volksschulabschluss", "Realschulabschluss (Mittlere Reife)", 
                                                                    "Abschluss Polytechnische Oberschule 10. Klasse (vor 1965: 8. Klasse)", 
                                                                    "Fachhochschulreife (Abschluss einer Fachoberschule)", "Abitur, allgemeine oder fachgebundene Hochschulreife (Gymnasium bzw. EOS)", 
                                                                    "Hochschulabschluss", "Anderer Schulabschluss:"), class = "factor")

    sjt.frq(testdata)

prints: 

![](http://dump.jemu.name/pEWP2.png)

yet 

    table(testdata)

shows the above table is wrong:

                                                             Noch Schüler 
                                                                        0 
                                            Schule beendet ohne Abschluss 
                                                                        0 
                                  Hauptschulabschluss/Volksschulabschluss 
                                                                        2 
                                      Realschulabschluss (Mittlere Reife) 
                                                                       31 
     Abschluss Polytechnische Oberschule 10. Klasse (vor 1965: 8. Klasse) 
                                                                        1 
                      Fachhochschulreife (Abschluss einer Fachoberschule) 
                                                                       13 
    Abitur, allgemeine oder fachgebundene Hochschulreife (Gymnasium bzw. EOS) 
                                                                       77 
                                                       Hochschulabschluss 
                                                                       66 
                                                  Anderer Schulabschluss: 
                                                                        2 

Any hints what causes this?

**Comment by jemus42** [comment]
*sigh*

Nevermind, the issue is gone in the current development versions of `sjPlot` (with the current version of `sjmisc`).

**Comment by sjPlot** [comment]
Yes, I guess it was the same problem as described in https://github.com/sjPlot/devel/issues/44 and https://github.com/sjPlot/devel/issues/2 and were fixed just a week ago... I think submission to CRAN will occure by the end of June...

**Comment by jemus42** [comment]
Nice. As long as you don't plan to introduce crippling changes to the devel-packages, I'm fine with using them for now.
