### ISSUE TITLE
Problem in frequency table with sort.frq = "asc" with Ñ (special spanish letter)

### ISSUE THREAD

**Issue by jfzeac** [sjPlot/devel#50]
First at all, thank you for your excellent work.

I made the next code sjt.frq(data$x, sort.frq  = "asc") and one of the levels (Mañana) is transform with NA.

I thank you if this issue can be fix.

Thank in advanced and congratulations for the great package

**Comment by sjPlot** [comment]
Do you have some data for reproducing an example? (e.g. output via `dput()`)

**Comment by jfzeac** [comment]
It appears work fine now, but I have a wa_rning

library(haven)
datos <- structure(c(1, 3, 5, 2, 2, 2, 3, 1, 3, 2, 2, 4, 2, 1, 1, 2, 1, 
                     2, 1, 2, 2, 1, 2, 2, 2, 5, 1, 5, 1, 3, 3, 3, 4, 2, 2, 2, 1, 2, 
                     3, 2, 4, 4, 2, 2, 2, 2, 2, 2, 4, 2, 3, 5, 5, 2, 2, 2, 2, 2, 2, 
                     5, 2, 1, 1, 2, 1, 2, 4, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 3, 1, 
                     1, 2, 1, 3, 2, 2, 5, 2, 2, 1, 2, 3, 2, 2, 2, 2, 4, 3, 1, 2),
                    labels = structure(c(1, 2, 3, 4, 5), .Names = c("Completa u ordinaria",
                            "Mañana", "Tarde",  "Noche", 
                             "Sabatina - Dominical")), class = "labelled")

sjt.frq(datos) #Fine!
  sjt.frq(datos,sort.frq = "desc") #warning
  
  
  sjt.frq(saber_2014II$JORNADA,sort.frq = "desc")

**Comment by sjPlot** [comment]
The warning is not relevant (at least in your case). It just tells you that - in case you have zero counts in categories - sorting may not be correct, do to wrong assignment of labels / values. Maybe I should convert the warning into a message, because most likely nothing wrong happened...

**Comment by jfzeac** [comment]
Thank you very much!
