### ISSUE TITLE
Actual p-values?

### ISSUE THREAD

**Issue by swvanderlaan** [sjPlot/devel#51]
Hi,
Would it be possible to pull-out the actual p-value from the lm/glm result? So, when p <0.001, not <0.001, but for instance p = 0.00045637, or p = 4.56e-5?

Would be great. Or is this already possible?

Thanks!

Sander

**Comment by sjPlot** [comment]
Is the current implementation in package versoin 1.8.2 sufficient enough?

> For "sjt.lm" and "sjt.glm", if "digits.p" is greater than 3, p-values less than 0.001 will no longer be abbreviated to "<0.001". Instead, the exact value (rounded to digits.p) will be printed.

**Comment by sjPlot** [comment]
I close this issue, assuming that the changes meet your needs. Feel free to re-open it, if the updates are not sufficient.
