### ISSUE TITLE
dates in view_spss

### ISSUE THREAD

**Issue by larmarange** [sjPlot/devel#53]
if `showType=T`, date variables are presented as atomic

**Comment by sjPlot** [comment]
Do you have a sample variable? I have not worked with date types in R yet, so what would be the vector class - `POSIXct`?

**Comment by sjPlot** [comment]
z <- Sys.time()
    str(z)
    > POSIXct[1:1], format: "2015-07-04 11:59:22"
    is.numeric.POSIXt(z)
    > [1] FALSE

**Comment by larmarange** [comment]
in Lubridate you have `is.Date` and `is.POSIXt` (with addition of all the other type of time variables available in that package)

**Comment by sjPlot** [comment]
Should work now. Feel free to re-open this issue, if something does not work as intended, or if there are date formats / classes not being detected.

**Comment by larmarange** [comment]
thanks

 Joseph

2015-07-04 14:18 GMT+02:00 Daniel Lüdecke <notifications@github.com>:
