### ISSUE TITLE
Extract a data frame from table functions of sjPlot 

### ISSUE THREAD

**Issue by jfzeac** [sjPlot/devel#54]
Good morning, First all, thank for your great package.

Is it possible to extract the output of a sjPlot table function in a data.frame, for example:

library(sjmisc)
data(efc)
a<- sjt.frq(efc$e42dep)

#Something like that
b<- sj-data.frame(a)

What can I do for solve the above issule?

Thank you in advance
José F. Zea

**Comment by sjPlot** [comment]
Currently, only the plotting functions return the data frame underlying the plot. However, I can add that feature to the table functions as well...

**Comment by sjPlot** [comment]
I was just wondering, which kind of output would be required? The raw data? The HTML code for the table? The table cells as data frame?

**Comment by andresimi** [comment]
Raw Data would be great!
