### ISSUE TITLE
Control colors in sjp.lm(fit, type = "ma")

### ISSUE THREAD

**Issue by jemus42** [sjPlot/devel#55]
While this function outputs many wonderful plots, I can't seem to control the colors I need to control.  
The help file states that this `type` ignores most arguments, including `geom.colors`, which is unfortunate. However, I am currently working on a project where using red in plots is not allowed, so plots like this ![](http://dump.jemu.name/RF6w9.png) are something I need to fix.

I understand that due to the large number of different plot types this function outputs, this is not an easy task, so I would be thankful for any hints on how to circumvent this, i.e. producing each plot via separate functions that offer color control, if possible?

**Comment by sjPlot** [comment]
I've modified the return value of this function type, so you now get a list of all plot outputs. You can then modify using the returned plot-object and add another scale:

    library(ggplot2)
    library(sjPlot)
    library(sjmisc)
    data(efc)
    fit <- lm(tot_sc_e ~ c12hour + e17age + e42dep, data = efc)
    dummy <- sjp.lm(fit, type = "ma")
    dummy$plot.list[[4]] + scale_color_manual(values = c("blue", "green"))

![rplot](https://cloud.githubusercontent.com/assets/4901179/8889192/4a1f58e0-32d0-11e5-8be1-ff1cfa3e2ad8.png)

However, if you're just interested in the forest plot: `sjp.lm(fit, type = "ma")` returns the updated model fit. You can then use the returned model in `sjp.lm(returned.model)` and use `geom.colors` then.

I'll commit the new changes tomorrow night, I have no access to GitHub upload right now.

**Comment by sjPlot** [comment]
P.S.: the plot you showed in your initial posting is simply the call to `sjp.lm(fit)`. Here you can ofcourse use the `geom.colors` argument.
