### ISSUE TITLE
waiver

### ISSUE THREAD

**Issue by leticiaocar** [sjPlot/devel#57]
I`m using R studio 3.1 and have installed sjmisc and sjPlot, but when I just started using the "sjp.int". Error in sjp.int(testeplot) : could not find function "waiver".

**Comment by sjPlot** [comment]
do you have `ggplot2` installed? `waiver()` is a ggplot-function. Does it work, when you load the ggplot2-library before using sjPlot?

**Comment by leticiaocar** [comment]
I havent installed. But now, after installed ggplot2, Another function is missing "Error in sjp.int(testeplot) : 
  could not find function "getInteractionTerms". Sorry, I dont know if there are others libraries required...

**Comment by sjPlot** [comment]
`getInteractionTerms` is a function inside the `sjPlot` package, which actually can't be missing. How have you installed the package? How are you using it?

    install.packages("sjPlot", dependencies = TRUE)
    library(sjPlot)
    ...
    sjp.int(...)

**Comment by leticiaocar** [comment]
I have installed using install.package. and attached: see bellow:
"> library("sjPlot", lib.loc="~/R/win-library/3.1")
Attaching package: ‘sjPlot’
The following object is masked _by_ ‘.GlobalEnv’:    sjp.int"
but when I try to use the function
> sjp.int(testeplot)
Error in sjp.int(testeplot) : 
  could not find function "getInteractionTerms"
It happens again. I really dont know what I am doing wrongly

**Comment by sjPlot** [comment]
> The following object is masked by ‘.GlobalEnv’: sjp.int"

that means that you have compiled a function names "sjp.int" from somewhere, which overrides the package-function. You have to remove `sjp.int` from your environment or clear your workspace to properly run sjPlot. R first searches for functions in the environment, than in attached packages. Hence, you are calling the "wrong" function as long as you still have an `sjp.int` function in your environment.
