### ISSUE TITLE
sjp.likert() doesn't work with knitr and latex output

### ISSUE THREAD

**Issue by nichtleiter** [sjPlot/devel#65]
Hi sir,

first of all i have to say thank you for the effort you put in this great package!

For high quality output i use kntir to create latex output and the tikz device to draw plots.
Unfortunately it doesn't work to create tikz output for a `sjp.likert()` plot because of the `%` percent sign. 

```
Error in getMetricsFromLatex(TeXMetrics) :
TeX was unable to calculate metrics for the following string
or character:

        100%

```

Is it possible to circumvent this error or adjust `sjPlot` so that latex output works?

Best regards

**Comment by nichtleiter** [comment]
I found a way without messing with `sjPlot`.

Knitr implements the chunk option `sanitize` which default value is `FALSE`. Setting this option tells `tikzDevice` to escape special Latex characters.

So executing 
```
opts_chunk$set(
     sanitize=TRUE
)
```
in the preamble solves my issue!

Best regards

**Comment by sjPlot** [comment]
Ok, thanks for looking into and solving this issue
