### ISSUE TITLE
sjPlot function

### ISSUE THREAD

**Issue by leticiaocar** [sjPlot/devel#66]
Hi daniel, 
i am still having trouble with sjp.int function. I reinstalled everything including R Studio because a virus problem in my pc. I clear my workspace as you suggested in July 30th:
"The following object is masked by ‘.GlobalEnv’: sjp.int"
that means that you have compiled a function names "sjp.int" from somewhere, which overrides the package-function. You have to remove sjp.int from your environment or clear your workspace to properly run sjPlot. R first searches for functions in the environment, than in attached packages. Hence, you are calling the "wrong" function as long as you still have an sjp.int function in your environment."
then I `ve installed using library(devtools) as is suggested on website to updates. So I `ve attached sjPlot, sjmisc, ggplot2 and when I try to use the function sjp.int, it seems something is still missing...
sjp.int(modz1)
Error in get(ctr, mode = "function", envir = parent.frame()) : 
  object 'contr.Treatment' of mode 'function' was not found

**Comment by sjPlot** [comment]
The [CRAN-Website](https://cran.r-project.org/package=sjPlot) lists all required (_Imports_) and suggested packages that are needed for **sjPlot** to work completely. Have you installed them as well?
