### ISSUE TITLE
remove.estimates

### ISSUE THREAD

**Issue by laurabnolan** [sjPlot/devel#67]
I don't think that remove.estimates is working. When I list even one variable to not include in the figure, it throws an error saying that this part of the expression is unused:

> sjp.glm(lm1.1, remove.estimates = "longterm")

Error in sjp.glm(lm1.1, remove.estimates = "longterm") : 
  unused argument (remove.estimates = "longterm")

Where "longterm" is the variable whose coefficient I would like removed from the graph. The regression model is specified as follows:

lm1.1 <- glm(formula = worse ~ mightdie + longterm + anydis + stunted + 
      foodshrt + puberty + female + wi + factor(pschool) + aschool + 
      factor(country), family = "binomial"(link = "logit"), data = health)

**Comment by sjPlot** [comment]
Are you using the correct package version?

See following reproducible example that works:

    library(sjmisc)
    data(efc)
    # create binary response
    y <- ifelse(efc$neg_c_7 < median(na.omit(efc$neg_c_7)), 0, 1)
    # create dummy variables for educational status
    edu.mid <- ifelse(efc$c172code == 2, 1, 0)
    edu.high <- ifelse(efc$c172code == 3, 1, 0)
    # create data frame for fitted model
    mydf <- data.frame(y = as.factor(y),
                       sex = as.factor(efc$c161sex),
                       dep = as.factor(efc$e42dep),
                       barthel = as.numeric(efc$barthtot),
                       edu.mid = as.factor(edu.mid),
                       edu.hi = as.factor(edu.high))
    # fit model
    fit <- glm(y ~., data = mydf, family = binomial(link = "logit"))
    # plot odds
    sjp.glm(fit)
    sjp.glm(fit, remove.estimates = "sex2")
    sjp.glm(fit, remove.estimates = c("dep2", "dep3", "dep4"))

**Comment by sjPlot** [comment]
Is `longterm` categorical? You have to use the same name as given by `summary`.

**Comment by laurabnolan** [comment]
Thank you! I’ve got it figured out.

Laura
