### ISSUE TITLE
suggestion: write_rda for sjmisc

### ISSUE THREAD

**Issue by frankcsliu** [sjPlot/devel#72]
I am wondering if it is possible to add labels drawn from sav files (via get_label() and get_labels()) into a rda file via write_rda? Is it possible to have write_csv?

**Comment by sjPlot** [comment]
If you save an object from your environment as `Rda` file, label attributes are already saved into that data file. CSV only allows to write plain text, thus, if you want "labelled" vectors, you can use `sjmisc::to_label` function to set labels as factor levels and then save the data to CSV. Should work. 

See [readr-package](https://cran.r-project.org/package=readr) for reading/writing CSV-/plain text files.
