### ISSUE TITLE
view_df() shows a broken table after using rec()

### ISSUE THREAD

**Issue by frankcsliu** [sjPlot/devel#74]
Hi, Daniel,  

My ideal work flow is (1) read_spss(),  (2) view_df(), (3) rec(), set_na(), and save(), and (4) view_df(the "cleaned" dataframe). 

I found that the variable and value labels of variables being recoded cannot being shown correctly in the last step. the vew_df() gives only the labels without any requested information. 

For example, V6 to V12 were recoded and now cannot show information. And the labels of variables later than V12 do not match well with the variables. 

![screen shot 2015-10-29 at 12 26 22 pm](https://cloud.githubusercontent.com/assets/12545793/10810098/5664c8a2-7e38-11e5-9dd1-a7599a16253e.png)

Did I miss any important step while using rec() and set_na()? Thank you.

**Comment by sjPlot** [comment]
Do you set value labels inside the function call to `rec`, or use `set_labels`? I need some further (reproducible code) information to investigate this issue.

**Comment by frankcsliu** [comment]
I used read_spss() to keep the labels. For example, 
id15 <- read_spss("~/BTSync/datasets/20150417_CountryIdentity/Total.sav",
                     option="foreign", 
                     enc = "big5", 
                     attach.var.labels = TRUE)  

Then I used rec() to recode variables.  For example, 
id15[, 8:15] <- rec(id15[,8:15], "1=1; 2=0", as.fac = F)  

I also used set_na() to recode NAs. Such as,
id15 <- set_na(id15, c(98:99, "NA")) 

I was wondering how to set labels for these variables all at once (Could I do that?). 
I did not do so before moving on to use view_df(). Then view_df() printed not-so-well-formatted frequency table.

**Comment by sjPlot** [comment]
> I was wondering how to set labels for these variables all at once (Could I do that?). 

Yes, use the `var.label` and `val.labels` arguments. Please See also *Note* section in `?sjmisc::rec`. This seems to be no issue of `view_df`.
