### ISSUE TITLE
a feature of set_na() wanted: select or drop variables

### ISSUE THREAD

**Issue by frankcsliu** [sjPlot/devel#75]
set_na() is a wonderful function and save me a lot of time. But here I need to skip one variable (age) that contains observations who are older than 98, while "98" in all of the rest variables should be set to na. Thank you.

**Comment by sjPlot** [comment]
Moved issue to sjmisc repo

**Comment by sjPlot** [comment]
as a workaround, you currently can use `dplyr::select`, and then use `dplyr::bind_cols` to bind the remaining variables like _age_ etc.

    new_df <- bind_cols(set_na(select(mydf, -age)), select(mydf, age))

**Comment by frankcsliu** [comment]
That is a nice solution. Thank you so much!
