### ISSUE TITLE
Question: Not show NA in graph

### ISSUE THREAD

**Issue by pvincentruz** [sjPlot/devel#77]
Hi I am using the command to plot interaction items

# plot regression line of interaction terms
sjp.int(model.girls.1.4A.fit , type = "eff", 
axisTitle.y = "Overall Mean of Girls' Post-Test z-scores",
 axisTitle.x ="Girls' Class Scientific Sensemaking mean", title = "Interaction of Girls' Class Scientific Sensemaking mean and Scientific Sensemaking on Girls Post-test z-scores")

And this is the graph I get:

<img width="499" alt="screen shot 2015-11-09 at 5 21 00 pm" src="https://cloud.githubusercontent.com/assets/15090470/11048487/33dbefaa-8706-11e5-85f8-a21a29770487.png">

Is there a way to make the line using the missing responses dissappear?

Thanks

**Comment by sjPlot** [comment]
Could you either post the summary of the model or even send the model object as `RData` file? I wonder why there should be `NA`s in the model's estimates.

**Comment by pvincentruz** [comment]
Sorry for the problem it was a problem on my code when I converted
something to a factor (Sleeps helps find this issues easier)

For thanks for the quick reply :)
