### ISSUE TITLE
sjp.frq histogram off by one

### ISSUE THREAD

**Issue by jemus42** [sjPlot/devel#79]
Example data:

```
load(url("http://stats.jemu.name/qm/data/ngo"))

» str(ngo$englisch)
 int [1:250] 1 2 5 3 5 3 3 3 3 0 ...
```
Produced plot:
```
sjp.frq(ngo$englisch, type = "hist")
```
![](http://dump.jemu.name/hxXSX.png)

Compared to the table:
```
» table(ngo$englisch)

 0  1  2  3  4  5  6  7  8  9 10 
 4  8 25 37 48 50 38 23 10  5  2 
```

EDIT: 
Interestingly, the normal curve is added correctly:

![](http://dump.jemu.name/euSOI.png)

**Comment by sjPlot** [comment]
This is a never-ending story, because I tried to deal with zero-values in non-labelled vectors. E.g., if a vector has possible value 1 to 4, but 3 never occurs in the vector, the result should be something like

    1  2  3  4
    4 19 0  5

There are always some cases (like your example) where it did not worked. I just rewrote the whole function that computed the frequency table, I hope it now works fine. However, for non-labelled numeric vectors, only valid values are printed (w/o "guessing" where zero-values might be).

**Comment by jemus42** [comment]
Huh, I did not assume that would be a problem, since every value from 0 to 10 occurs in the specific frequency table.

Just curious: Why not just use the basic ggplot2 `geom_histogram`?

**Comment by sjPlot** [comment]
> s1 <- c(1,2,1,2,3,3,2,5,6,5,6,2,1)
    > table(s1)
    s1
    1 2 3 5 6 
    3 4 2 2 2 

Value `4` does not appear in the table. However, you _could_ assume that you have a continuous variable, where 4 has just no count, so a `0` for 4 would be appropriate.

**Comment by sjPlot** [comment]
Ok, works fine with my current sjPlot-build. I'll commit the latest update soon, so issue closed for now.

**Comment by jemus42** [comment]
I don't see how that applies to my issue, where the table looks like this:

```
» table(ngo$englisch)

 0  1  2  3  4  5  6  7  8  9 10 
 4  8 25 37 48 50 38 23 10  5  2 
```

The values from 0 to 10 are present and have `>0` frequencies.

As I write this comment, you closed the issue, so I'll just let it go and assume you know what's going on :)  
Thanks.

**Comment by sjPlot** [comment]
My "strange" algorithm to guess zero values was the cause for your bug, because it sometimes gave troubles with numeric vectors starting at zero. ;-)

You have to install the latest commit from sjmisc before sjPlot works.

**Comment by sjPlot** [comment]
btw, use `type = "bar"` for proper axis range, or if you use `hist`, also use `axisLimits.x = c(-1, 11)` or something.

**Comment by sjPlot** [comment]
sjp.frq(ngo$englisch, type = "hist", showNormalCurve = T, 
               showMeanIntercept = T, axisLimits.x = c(-1, 11))

![rplot](https://cloud.githubusercontent.com/assets/4901179/11320770/6068269e-90a5-11e5-9734-379ec2e56303.png)

**Comment by jemus42** [comment]
Thanks a lot!  

<3
