### ISSUE TITLE
possible bug in sjt.itemanalysis

### ISSUE THREAD

**Issue by rolfmblindgren** [sjPlot/devel#8]
Please consider the following:

    > P.min <- P[1:10,1:10]
    > P.min
       6036 6053 6054 6037 6055 6056 6057 6058 6059 6060
    1     1    1    1    1    1    1    1    1    1    1
    2     0    1    1    1    1    1    1    1    0    1
    3     1    0    1    1    1    1    1    1    1    1
    4     0    1    1    0    1    0    0    1    1    1
    5     1    1    1    1    1    1    1    1    1    1
    6     0    1    1    1    1    1    1    1    1    1
    7     0    0    1    0    0    1    1    1    1    1
    8     1    1    1    0    1    1    1    1    1    1
    9     1    1    1    1    0    0    1    1    1    1
    10    1    0    0    1    0    1    0    0    1    0

The result is

      |======================================================================| 100%
    Error in gsub("      <", "<", html.table, fixed = TRUE) : 
      object 'toWrite' not found

I have attempted the same with larger tables. P.min is an arbitrary subset of a larger table (36 columns, 2466 rows).

Any clues? 

Much appreciated,
- roffe

**Comment by sjPlot** [comment]
Thanks for your feedback, I found the bug and fixed it. Meanwhile, add `remove.spaces = F` to your sjt.itemanalysis-function call as a workaround: `sjt.itemanalysis(df, remove.spaces = F)`
