### ISSUE TITLE
error in response variable family

### ISSUE THREAD

**Issue by brunomelati** [sjPlot/devel#80]
Dears,

I am trying to plot a sjp.int for my ecological data. At the response variable I have count data, but in the y axis it's appearing as predicted probability. I could not find how to change the family from binomial to poisson. 

I have already check all my data and the models that I am trying to plot, and they are correct. 

Do you know why this problem is happening? 

The model that I am trying to plot is:

m1=glmer ( resp. variable~fixed variable1 + fixed variable2 + fixed variable1:fixed variable2 + 
       (1| random variable/ nested random variable), family = poisson, data )

sjp.int(m1,type = 'eff', diff = FALSE, moderatorValues = 'minmax', swapPredictors = TRUE)

Thank you

**Comment by sjPlot** [comment]
That's a shortcoming of both the documentation and the `sjp.int`-function. Currently, only binomial (logit) family is supported for most / all of the sjp-functions.

I'm not sure what the `predict` function is predicting for poisson regression, see also [my question at SO here](http://stackoverflow.com/questions/33215517/equivalent-to-plogislogit-for-poisson-family-in-r). If I know how to predict incidents, I would implement poisson-family support...

**Comment by sjPlot** [comment]
Ok, I guess I found a solution on how to integrate poisson family. Working on an update...

**Comment by sjPlot** [comment]
For `type = "eff"`, this should work now. Could you please confirm this?

**Comment by brunomelati** [comment]
Dear Daniel,

Than you. I'll check as son as possible. I'll give you a feedback.

Best wishes

Bruno Melati

Enviado via iPhone

Em 28/01/2016, às 17:28, Daniel Lüdecke <notifications@github.com> escreveu:

**Comment by sjPlot** [comment]
Any news on this issue? sjPlot 1.9.1 has just been released, this issue should be fixed now.

**Comment by brunomelati** [comment]
Prized, 

It is working correctly.

Thank you for your dedication.

Enviado via iPhone

Em 10/02/2016, às 07:24, Daniel Lüdecke <notifications@github.com> escreveu:
