### ISSUE TITLE
sjp.xtab not working with current version of ggplot2?

### ISSUE THREAD

**Issue by ebergel** [sjPlot/devel#82]
sjp.xtab does not seem to work with an updated version of ggplot2?

this minimal example produce an error

library(sjPlot)
grp <- sample(1:4, 100, replace = TRUE)
x <- sample(1:3, 100, replace = TRUE)
sjp.xtab(x, grp)

> sjp.xtab(x, grp)
Error: Aesthetics must be either length 1 or the same as the data (15): hjust, vjust

I think the error is in ggplot2:   ggplot2/R/geom-.r

stop(
    "Aesthetics must be either length 1 or the same as the data (", n, "): ",
    paste(names(!good), collapse = ", "),
    call. = FALSE
  )

I downgraded ggplot2 to an older version (1.0.1) and is working ok now.

**Comment by sjPlot** [comment]
ggplot got some major changes, which I have to fix step by step now. this will take a while... If you find any more issues, please open an issue here so I can track down all incompatibilities with ggplot2 2.0

**Comment by ebergel** [comment]
Ok, and thanks for such a fantastic R package.

**Comment by sjPlot** [comment]
should be fixed now.
