### ISSUE TITLE
ggplot2 2.0

### ISSUE THREAD

**Issue by rubenarslan** [sjPlot/devel#84]
Some warnings that now occur frequently when using sjPlot:

4: replacing previous import by 'grid::unit' when loading 'sjPlot' 

2: `show_guide` has been deprecated. Please use `show.legend` instead.

**Comment by sjPlot** [comment]
Ok, these should be fixed now. A new update will take some time because I have to change code in many places due to the ggplot2 update, and I'm also changing / updating some functions and code which is not related to ggplot2.
