### ISSUE TITLE
y axis goes from 0 to 1 for binomial glms

### ISSUE THREAD

**Issue by rubenarslan** [sjPlot/devel#86]
Instead of shrinking to the range of the observed effects. That way you can't see small effects. I don't really see why this should be the (default) behaviour anyway, but maybe it could be optionally turned off.

Workaround is: `sjp.int(by_method, type = "eff", showCI = F, printPlot = F, plevel = 1)$plot.list[[1]] + ylim(0.5,0.6)`, but would require some work to first get actual range of effects from df.list.

**Comment by sjPlot** [comment]
I could set a default value set to `auto` to zoom the axis to required range.

**Comment by rubenarslan** [comment]
I think that would make sense :-)
