### ISSUE TITLE
Error: Unknown parameters: family

### ISSUE THREAD

**Issue by rozhnoel** [sjPlot/devel#87]
Hi,
I am wondering why i am getting the above error i Rstudio when I am trying to run the code
sjp.glm(fit, 
        axisLabels.y = predlab,
        type = "prob",
        show.se = TRUE)
as exactly supplied by the sjplot page. 

the packages, R, and Rstudio are up--to-date.

Thanks in advance.

**Comment by sjPlot** [comment]
fixed.
