### ISSUE TITLE
Error: Aesthetics must be either length 1 or the same as the data (5): label, hjust, vjust

### ISSUE THREAD

**Issue by danielmarcelino** [sjPlot/devel#88]
I'm having this message when plotting `sjp.frq`; It use to work at some point before, but somehow it's notting plotting anymore.

**Comment by sjPlot** [comment]
It's due to the major update of ggplot. An update of sjPlot fixing these issues should be ready by the end of next week (CRAN deadline).

**Comment by danielmarcelino** [comment]
Ok thanks

**Comment by sjPlot** [comment]
Which functions are affected? I'm asking because I don't want to miss something.

**Comment by sjPlot** [comment]
At least for `sjp.frq`, this issue is fixed.
