### ISSUE TITLE
sjp.lmer: Error in diag(vcov(object)[parm, parm, drop = FALSE])

### ISSUE THREAD

**Issue by ashenkin** [sjPlot/devel#89]
Hi there,

I'm getting the following error when trying to plot fixed effects in sjp.lmer:

````
> sjp.lmer(allom_r_width_loglog_lmer, type = "fe")
Error in diag(vcov(object)[parm, parm, drop = FALSE]) : 
  error in evaluating the argument 'x' in selecting a method for function 'diag': Error in .Primitive("[")(x = as(x, "matrix"), i = i, j = j, drop = drop) : 
  subscript out of bounds
````

Happy to send the data along to verify the issue, but prefer not to post it publicly...

**Comment by sjPlot** [comment]
Yes, some data to reproduce this issue would be helpful. Would be glad if you could send it via mail.

**Comment by ashenkin** [comment]
Thanks Daniel - just sent to d.luedecke at uke.de

**Comment by ashenkin** [comment]
update: just updated to r 3.2.3, along with updating ggplot and everything else, and this now works...

**Comment by sjPlot** [comment]
Ok thanks. sjPlot should currently not work with ggplot 2.0, update is on the way

**Comment by ashenkin** [comment]
Hmm, this was done with ggplot2, but will keep eyes open for update
regardless, thanks.

**Comment by sjPlot** [comment]
the ggplot2-update may not affect all plotting-functions in sjPlot, I'll have to check this carefully and fix bugs the next days.
