### ISSUE TITLE
Something wrong with the sjt.xtab results!

### ISSUE THREAD

**Issue by rozhnoel** [sjPlot/devel#90]
The results show two strange things compared to the xtabs of the R. 
First, the column/row names have opposite values to those with R xtabs.
Second, the default row/col labels are missing one option and instead shows NA while there is no NA in the dataset.

Any ideas,

Regards
R Noel

**Comment by sjPlot** [comment]
Do you have a reproducible example?

**Comment by rozhnoel** [comment]
Hi,

sorry for the late answer, here is an example:

in sjplot:

sjt.xtab(er$V216,er$RV)

var.row	var.col	Total
Nej	Ja
Pre	0	791	791
Co_IO	0	1575	1575
RV_IO	0	1093	1093
RV_Post	1205	0	1205
NA	565	0	565
Total	1770	3459	5229
Χ2=5229.000 · df=4 · Φc=1.000 · p<.001

in ftable in R:

> ftable(table(er$V216,er$RV))
           Ja  Nej
                  
Co_IO       0  791
Co_Post     0 1575
Pre         0 1093
RV_IO    1205    0
RV_Post   565    0

Sorry for the formatting. There is a row (NA) in the sjplot part with 565 results should be RV_Post, for example. The subset does not include NAs. Somethings goes wrong with the row names and not the calculations.

Regards
Rozh

**Comment by sjPlot** [comment]
I would need the data to reproduce the example.

**Comment by sjPlot** [comment]
Could you check with the latest version of sjPlot 1.9? I guess this issue might be fixed now.

**Comment by rozhnoel** [comment]
Hi,

Is version 1.9 available for mac?
It not available in CRAN!

**Comment by sjPlot** [comment]
mac builds may take some days... you can also install from github.

**Comment by rozhnoel** [comment]
I get this error when i install fr github
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘sjmisc’ 1.3 is already loaded, but >= 1.4 is required
Error: package or namespace load failed for ‘sjPlot’

Installation does not work!

**Comment by sjPlot** [comment]
Ok, in this case you have to update the sjmisc Package as well. I suggest runnning `update.packages()` first.

**Comment by rozhnoel** [comment]
Hi,

I updated and it worked beautifully.
Thanks for the great work!!

R Noel

**Comment by sjPlot** [comment]
Ok, thanks for the feedback!
