### ISSUE TITLE
Error when using type = "prob" with sjp.glm

### ISSUE THREAD

**Issue by cedricbatailler** [sjPlot/devel#92]
Hi,

I got a recurrent error when trying to use `type = "prob"` with `sjp.glm()`. I also got this error when using `sjp.glmer()` (`type = "fe.pc"` or `type = "fe.prob"`). 

Error message is : `Error: Unknown parameters: family`.

Here's the error and here's a reproducible example:
```r
library(sjPlot)

df = data.frame(x = c(10, 20, 30, 40, 50, 60, 70, 80),
                y = c(1, 1, 0, 1, 1, 0, 0, 0))

m1 = glm(data = df, y ~ x, family = binomial)
sjp.glm(fit = m1, type = "prob")
```

**Comment by sjPlot** [comment]
should be due to changes in `ggplot2::stat_smooth` and is fixed now. I just submitted an update to CRAN. Please check if this error still occurs with sjPlot 1.9
