### ISSUE TITLE
Partial matching

### ISSUE THREAD

**Issue by helix123** [sjPlot/devel#95]
with sjPlot 1.9 I get warnings about partial matches (when the warning option is turned on):
Here is an example:
````
options(warnPartialMatchAttr   = TRUE,
        warnPartialMatchDollar = TRUE,
        warnPartialMatchArgs   = TRUE)

data(mtcars)
mod <- lm(mpg ~ cyl + disp + hp + disp:hp, data=mtcars)
sjp.int(mod)
# Warning in seq.default(pos[i, 1], length = pos[i, 2]) :
#   partial argument match of 'length' to 'length.out'
# Warning in seq.default(pos[i, 1], length = pos[i, 2]) :
#   partial argument match of 'length' to 'length.out'
````
More functions could be affected, have not tried all. It is not really a problem but maybe worth to fix for code clarity?

**Comment by sjPlot** [comment]
Since RCMD check also checks for partial matching it might be an issue of another package used by sjPlot but I will check this.

**Comment by helix123** [comment]
Oh, R CMD check already checks for that? Here is a suggestion on R-devel to add that feature to R CMD check: https://stat.ethz.ch/pipermail/r-devel/2016-January/072230.html

**Comment by sjPlot** [comment]
Maybe it was the RStudio diagnostics feature. I remember that I was warned about partial matching and fixed them in my source - however, I don't exactly remember who warned me ;-)

Anyway, I can't find any conspicuous parts in my source where I use `seq` with `length` argument in `sjp.int`.

**Comment by sjPlot** [comment]
Ok, I searched all code files in both packages (sjPlot and sjmisc), and I have not used any `length=` nor `length =` - however, always `length.out`. So it's very likely to be an issue of another package.

**Comment by helix123** [comment]
Thank your for having a look. I diagnosed that further and found an easy way to find the right spot: use
`options(showWarnCalls = TRUE)` to see where the partial matching occurs. In this case we get
````
# Warning in seq.default(pos[i, 1], length = pos[i, 2]) :
#  partial argument match of 'length' to 'length.out'
# Calls: sjp.int ... list_to_dataframe -> rbind.fill -> seq -> seq.default
# Warning in seq.default(pos[i, 1], length = pos[i, 2]) :
# partial argument match of 'length' to 'length.out'
# Calls: sjp.int ... list_to_dataframe -> rbind.fill -> seq -> seq.default
````
It is in package `plyr` (or futher down the road), see:
````
a <- data.frame(z = c(1,2,3), y =c(2,3,4))
b <- data.frame(z = c(7,8,9))
plyr::rbind.fill(a, b)
````

**Comment by sjPlot** [comment]
So it's probably due to ggplot, which relies on plyr?

**Comment by helix123** [comment]
I guess so, yes (`ggplot2`). It seems already fixed in the dev version of `plyr`.
