### ISSUE TITLE
compare summary result of sjt.xtab with sjp.xtab or sjp.grpfrq

### ISSUE THREAD

**Issue by aparnitzke** [sjPlot/devel#99]
Why does the summary result (Degrees of freedom, Fisher's excact test, Chi-square statistics or Phi-value) in sjt.xtab differ from sjp.xtab or sjp.grpfrq? Using the same data, I would expect the same result. Or do I understand something wrong.

sjt.xtab(efc$e42dep, efc$e16sex)
sjp.xtab(efc$e42dep, efc$e16sex, showTableSummary = TRUE)
sjp.grpfrq(efc$e42dep, efc$e16sex, showTableSummary = TRUE)

**Comment by aparnitzke** [comment]
Thanks. Now only the Fisher's excact test is different between sjt.xtab and sjp.xtab or sjp.grpfrq.

**Comment by sjPlot** [comment]
Ok, it seems that [`simulate.p.value`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/fisher.test.html) is the reason for this. Repeating the test does compute different p-values.
